////
     Licensed to the Apache Software Foundation (ASF) under one
     or more contributor license agreements.  See the NOTICE file
     distributed with this work for additional information
     regarding copyright ownership.  The ASF licenses this file
     to you under the Apache License, Version 2.0 (the
     "License"); you may not use this file except in compliance
     with the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing,
     software distributed under the License is distributed on an
     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
     KIND, either express or implied.  See the License for the
     specific language governing permissions and limitations
     under the License.
////
= Getting Started with the Apache NetBeans Platform / Apache NetBeans
:jbake-type: page
:jbake-tags: community
:jbake-status: published
:keywords: Apache NetBeans Getting Started with Platform
:description: For those interested in using Apache NetBeans as their Java Desktop Platform
:toc: left
:toc-title:

== Getting Started with the Apache NetBeans Platform

This is for those interested in using Apache NetBeans as the basis of their own
software, i.e., using Apache NetBeans as a Java desktop platform.

There are also convenience binaries on netbeans.apache.org that you could use,
instead of building from the sources, though if you're involved in the Apache
NetBeans project it makes most sense to use the sources since you can then
provide pull requests to fix bugs you encounter or to provide enhancements.

=== Part I: Hello, Apache NetBeans Platform

First steps in getting started with Apache NetBeans as the basis of your own Java desktop software.

video::VC8gQJknPaU[youtube]

=== Part II: Debugging into the Apache NetBeans Platform

Once you have an Apache NetBeans Platform application set up, how do you debug
into the sources of the Apache NetBeans Platform itself?

video::rufG7VE-u9s[youtube]

=== Part III: Run & Debug Apache NetBeans IDE

A quick tip for running and debugging Apache NetBeans IDE.

video::a1F2FkhZfQM[youtube]

=== Part IV: Edit and Run Apache NetBeans IDE

How do you make changes to the source code and then see them live in Apache NetBeans IDE?

video::iv4osiFZDP0[youtube]

=== Part V: Debug the Sources of Apache NetBeans IDE

How to debug into the source code of Apache NetBeans IDE? Find out here.

video::UaGdctQWt_4[youtube]
