= NetBeans templates

Templates are Groovy Server Pages that will be filled-in with elements in the link:../content[content directory].

== Creating templates

This directory contains some templates for different types of pages.

*NOTE:* As a good practice, if you open an HTML tag in one template make sure the tag *is also closed in the same* template.

*NOTE:* Templates must be also manually added to the file `jbake.properties`

== Main templates

These are the main templates used in this project. Files ending in `.gsp` are "Groovy Server Pages" pages, this is, can be scripted using Groovy:

=== Complete page templates

- *page.gsp* A skeleton for plain HTML 5 pages, with a `hero` banner. An aside on the right hosts the table of contents of the content.
- *page-noaside.gsp* A skeleton for the main page (without asides).

=== Web page parts

These parts are included in the

- *head.gsp* The `<head>` tag for all pages.
- *footer.gsp* The footer section for all pages.
- *menu.gsp* The NetBeans web site menu.



