////
     Licensed to the Apache Software Foundation (ASF) under one
     or more contributor license agreements.  See the NOTICE file
     distributed with this work for additional information
     regarding copyright ownership.  The ASF licenses this file
     to you under the Apache License, Version 2.0 (the
     "License"); you may not use this file except in compliance
     with the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing,
     software distributed under the License is distributed on an
     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
     KIND, either express or implied.  See the License for the
     specific language governing permissions and limitations
     under the License.
////
= Plugins / Apache NetBeans
:jbake-type: page
:jbake-tags: community
:jbake-status: published
:keywords: Apache NetBeans plugins modules
:description: Apache NetBeans Plugins
:toc: left
:toc-title:
:debug: yes

== Apache NetBeans Plugins

The NetBeans IDE and the NetBeans Platform are built on top of a modular architecture, and can be enhanced with plugins. 

We are currently transitioning the plugin portal to the new Apache infrastructure. Some plugins won't be able to be hosted in Apache infrastructure due to licensing issues.

Apache NetBeans 9.0 Beta uses the same update center as in previous versions, so you should be able to install plugins (hosted outside the Apache infrastructure) designed for previous versions of NetBeans. You will be asked to accept the appropriate license agreement for any plugins you install.

Please visit the previous link:http://plugins.netbeans.org/PluginPortal/[NetBeans Plugin Portal] for more information about NetBeans plugins.




