////
     Licensed to the Apache Software Foundation (ASF) under one
     or more contributor license agreements.  See the NOTICE file
     distributed with this work for additional information
     regarding copyright ownership.  The ASF licenses this file
     to you under the Apache License, Version 2.0 (the
     "License"); you may not use this file except in compliance
     with the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing,
     software distributed under the License is distributed on an
     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
     KIND, either express or implied.  See the License for the
     specific language governing permissions and limitations
     under the License.
////
////

NOTE: 
See https://www.apache.org/dev/release-download-pages.html 
for important requirements for download pages for Apache projects.

////
= Apache NetBeans Releases
:jbake-type: page
:jbake-tags: download
:jbake-status: published
:keywords: Apache NetBeans releases
:icons: font
:description: Apache NetBeans Releases Page
:syntax: true
:source-highlighter: pygments
:experimental:
:linkattrs:

Apache NetBeans is released four times a year. For details, see link:https://cwiki.apache.org/confluence/display/NETBEANS/Release+Schedule[full release schedule].

== Apache NetBeans 16

Latest version of the IDE, released on November 30, 2022.

xref:nb16/index.adoc[Download, role="button success"]

== Older releases

Older Apache NetBeans releases can still be downloaded, but are no longer supported.

xref:archive/index.adoc[Find out more, role="button"]

== Daily builds and building from source

All Apache NetBeans source code is freely available to build yourself, or you can
download (unsupported) daily development builds.

xref:dev/index.adoc[Find out more, role="button"]
