////
     Licensed to the Apache Software Foundation (ASF) under one
     or more contributor license agreements.  See the NOTICE file
     distributed with this work for additional information
     regarding copyright ownership.  The ASF licenses this file
     to you under the Apache License, Version 2.0 (the
     "License"); you may not use this file except in compliance
     with the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing,
     software distributed under the License is distributed on an
     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
     KIND, either express or implied.  See the License for the
     specific language governing permissions and limitations
     under the License.
////
////

NOTE: 
See https://www.apache.org/dev/release-download-pages.html 
for important requirements for download pages for Apache projects.

////
= Downloads / Apache NetBeans
:jbake-type: page
:jbake-tags: download
:jbake-status: published
:keywords: Apache NetBeans download
:description: Apache NetBeans Download page
:toc: left
:toc-title:

[[releases]]
== Releases

=== Apache NetBeans 9.0

- link:nb90/[Apache NetBeans 9.0 Features]
- link:nb90/nb90.html[Apache NetBeans 9.0], released on the 29th of July, 2018.
- link:nb90/nb90-rc1.html[Apache NetBeans 9.0 RC1], released on the 28th of May, 2018.
- link:nb90/nb90-beta.html[Apache NetBeans 9.0 Beta], released on the 22nd of February, 2018.

[[downloading]]
=== Downloading

////
NOTE: It's mandatory to link to the source. It's optional to link to the binaries.
NOTE: It's mandatory to link against dist.apache.org for the sums & keys. https is recommended.
////
Apache NetBeans 9.0 is available for download from your closest Apache mirror. For this release no official installers are provided, please just download the binaries and unzip them.

- Source: link:https://www.apache.org/dyn/closer.cgi/incubator/netbeans/incubating-netbeans-java/incubating-9.0/incubating-netbeans-java-9.0-source.zip[incubating-netbeans-java-9.0-source.zip] (
link:https://www.apache.org/dist/incubator/netbeans/incubating-netbeans-java/incubating-9.0/incubating-netbeans-java-9.0-source.zip.asc[PGP ASC],
link:https://www.apache.org/dist/incubator/netbeans/incubating-netbeans-java/incubating-9.0/incubating-netbeans-java-9.0-source.zip.sha1[SHA-1])
- Binaries: link:https://www.apache.org/dyn/closer.cgi/incubator/netbeans/incubating-netbeans-java/incubating-9.0/incubating-netbeans-java-9.0-bin.zip[incubating-netbeans-java-9.0-bin.zip] (
link:https://www.apache.org/dist/incubator/netbeans/incubating-netbeans-java/incubating-9.0/incubating-netbeans-java-9.0-bin.zip.asc[PGP ASC],
link:https://www.apache.org/dist/incubator/netbeans/incubating-netbeans-java/incubating-9.0/incubating-netbeans-java-9.0-bin.zip.sha1[SHA-1])

*Note:* Apache NetBeans community member Carl Mosca has made link:https://github.com/carljmosca/netbeans-macos-bundle[a Mac OSX installation bundle available here].

Also see the following YouTube clips:

link:https://www.youtube.com/watch?v=am-7aa2hYgc[Get Started with NetBeans from a ZIP Archive]

link:https://www.youtube.com/watch?v=I8gdC7BBtbs[Get Started with NetBeans from a Mac OSX Installer]

////
NOTE: Using https below is highly recommended.
////
Officially, it is important that you link:https://www.apache.org/dyn/closer.cgi#verify[verify the integrity] of the downloaded files using the PGP signatures (.asc file) or a hash (.sha1 files).  The PGP keys used to sign this release are available link:https://dist.apache.org/repos/dist/release/incubator/netbeans/KEYS[here].

[[latest]]
== Latest Builds

link:https://jenkins.io/index.html[Jenkins] is quite busy link:https://builds.apache.org/view/Incubator%20Projects/job/incubator-netbeans-linux/lastSuccessfulBuild/artifact/[creating our latest builds].

[[source]]
== Building from source

You can of course build Apache NetBeans from source. To do so:

. Clone the https://github.com/apache/incubator-netbeans GitHub repository.
. Install Oracle's Java 8 or Open JDK v8.
. Install Apache Ant 1.10 or greater (https://ant.apache.org/).

Once you're all set just enter the `incubator-netbeans` directory and type:

- `ant` to build the Apache NetBeans IDE.
  ** Once built, the IDE bits are placed in the `./nbbuild/netbeans` directory. You can run the IDE from within the `incubator-netbeans` directory by typing `./nbbuild/netbeans/bin/netbeans` on unixes (for Windows the command is equivalent).
- `ant tryme` to run the Apache NetBeans IDE.

For details, go here: https://cwiki.apache.org/confluence/display/NETBEANS/Development+Environment

Now that you have built Apache NetBeans from source you may want to link:/participate/submit-pr.html[submit a pull request].

[[repos]]
=== Repositories

This is a list of Apache NetBeans (incubating) repositories:

- https://github.com/apache/incubator-netbeans The main source code repository.
- https://github.com/apache/incubator-netbeans-website This website's repository.
- https://github.com/apache/incubator-netbeans-website-cleanup A repository used to clean up existing documentation from http://netbeans.org
- Emilian Bold has converted the previous Mercurial repository (http://hg.netbeans.org) to git, for historical reference, and has kindly uploaded it to GitHub at https://github.com/emilianbold/netbeans-releases. Thanks, Emilian!

[[previous]]
== Previous NetBeans versions

You can download previous Apache NetBeans versions by visiting https://archive.apache.org/dist/incubator/netbeans/, while pre-Apache NetBeans versions are at https://netbeans.org/downloads/.

