////
     Licensed to the Apache Software Foundation (ASF) under one
     or more contributor license agreements.  See the NOTICE file
     distributed with this work for additional information
     regarding copyright ownership.  The ASF licenses this file
     to you under the Apache License, Version 2.0 (the
     "License"); you may not use this file except in compliance
     with the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing,
     software distributed under the License is distributed on an
     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
     KIND, either express or implied.  See the License for the
     specific language governing permissions and limitations
     under the License.
////
////

NOTE: 
See https://www.apache.org/dev/release-download-pages.html 
for important requirements for download pages for Apache projects.

////
= Apache NetBeans Releases
:jbake-type: page
:jbake-tags: download
:jbake-status: published
:keywords: Apache NetBeans releases
:description: Apache NetBeans Releases Page
:toc: left
:toc-title:
:linkattrs:

[[releases]]

== Apache NetBeans 11.0

Apache NetBeans 11.0 is the latest version of the IDE. It was released on April 4, 2019.

link:nb110/index.html[Features, role="button"] link:nb110/nb110.html[Download, role="button success"]


== Apache NetBeans 10.0

Apache NetBeans 10.0 was released on December 27, 2018.

link:nb100/index.html[Features, role="button"] link:nb100/nb100.html[Download, role="button success"]

[[previous]]
== Apache NetBeans 9.0

Apache NetBeans 9.0 was released on the July 29, 2018.

link:nb90/[Features, role="button"] link:nb90/nb90.html[Download, role="button success"] 

== Pre-Apache NetBeans versions

- https://netbeans.org/downloads/8.2/
- https://netbeans.org/downloads/8.1/
- https://netbeans.org/downloads/8.0/
- https://netbeans.org/downloads/7.4/

== Release schedule

Please visit the link:https://cwiki.apache.org/confluence/display/NETBEANS/Release+Schedule[release schedule page] for the full release schedule.

[[source]]
== Building from source

You can of course build Apache NetBeans from source. To do so:

. Clone the https://github.com/apache/netbeans GitHub repository.
. Install Oracle's Java 8 or Open JDK v8.
. Install Apache Ant 1.10 or greater (https://ant.apache.org/).

Once you're all set just enter the `netbeans` directory and type:

- `ant` to build the Apache NetBeans IDE.
  ** Once built, the IDE bits are placed in the `./nbbuild/netbeans` directory. You can run the IDE from within the `netbeans` directory by typing `./nbbuild/netbeans/bin/netbeans` on unixes (for Windows the command is equivalent).
- `ant tryme` to run the Apache NetBeans IDE.

For details, go here: https://cwiki.apache.org/confluence/display/NETBEANS/Development+Environment

Now that you have built Apache NetBeans from source you may want to link:/participate/submit-pr.html[submit a pull request].

[[repos]]
=== Repositories

This is a list of Apache NetBeans repositories:

- https://github.com/apache/netbeans The main source code repository.
- https://github.com/apache/netbeans-website This website's repository.
- https://github.com/apache/netbeans-website-cleanup A repository used to clean up existing documentation from http://netbeans.org
- Emilian Bold has converted the previous Mercurial repository (http://hg.netbeans.org) to git, for historical reference, and has kindly uploaded it to GitHub at https://github.com/emilianbold/netbeans-releases. Thanks, Emilian!


