github:
  description: "Apache NetBeans Website"
  homepage: "https://netbeans.apache.org/"
  labels:
    - netbeans
    - website
    - antora
publish:
  whoami: asf-site

staging:
  profile: antora # See https://cwiki.apache.org/confluence/display/INFRA/git+-+.asf.yaml+features#Git.asf.yamlfeatures-Stagingawebsitepreviewdomain
  whoami: antora
