////
     Licensed to the Apache Software Foundation (ASF) under one
     or more contributor license agreements.  See the NOTICE file
     distributed with this work for additional information
     regarding copyright ownership.  The ASF licenses this file
     to you under the Apache License, Version 2.0 (the
     "License"); you may not use this file except in compliance
     with the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing,
     software distributed under the License is distributed on an
     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
     KIND, either express or implied.  See the License for the
     specific language governing permissions and limitations
     under the License.
////
////

NOTE: 
See https://www.apache.org/dev/release-download-pages.html 
for important requirements for download pages for Apache projects.

////
= Apache NetBeans Releases
:jbake-type: page
:jbake-tags: download
:jbake-status: published
:keywords: Apache NetBeans releases
:description: Apache NetBeans Releases Page
:toc: left
:toc-title:
:linkattrs:

== Mirror selection
////
  use  raw html to replace bracket items with apache mirror with the cgi script
////
++++
<p>
[if-any logo]
   <a href="[link]"><img align="right" src="[logo]" border="0" alt="logo"/></a>
[end]

The currently selected mirror is <b>[preferred]</b>.
If you encounter a problem with this mirror,please select another mirror.
If all mirrors are failing, there are <i>backup</i> mirrors (at the end of the mirrors list) that should be available.
</p>

        <form action="[location]" method="get" id="SelectMirror">
          Other mirrors:
          <select name="Preferred">
            [if-any http]
            [for http]
            <option value="[http]">[http]</option>
            [end]
            [end]
            [if-any ftp]
            [for ftp]
            <option value="[ftp]">[ftp]</option>
            [end]
            [end]
            [if-any backup]
            [for backup]
            <option value="[backup]">[backup] (backup)</option>
            [end]
            [end]
          </select>
          <input type="submit" value="Change"/>
        </form>

<p>
   You may also consult the <a href="https://www.apache.org/mirrors/">complete list of mirrors.</a>
</p>

++++

== Apache NetBeans parent pom 2 

|===
| | Links  | Checksum | Signature

|Apache NetBeans parent pom 2 | link:++[preferred]netbeans/netbeans-parent/netbeans-parent-2/netbeans-parent-2-source-release.zip++[netbeans-parent-2-source-release.zip] | link:++https://downloads.apache.org/netbeans/netbeans-parent/netbeans-parent-2/netbeans-parent-2-source-release.zip.sha512++[netbeans-parent-2-source-release.zip.sha512] | link:++https://downloads.apache.org/netbeans/netbeans-parent/netbeans-parent-2/netbeans-parent-2-source-release.zip.asc++[netbeans-parent-2-source-release.zip.asc]

|===


== Previous Versions

Older non-recommended releases can be found on our link:https://archive.apache.org/dist/netbeans/[archive of netbeans]
