
////
     Licensed to the Apache Software Foundation (ASF) under one
     or more contributor license agreements.  See the NOTICE file
     distributed with this work for additional information
     regarding copyright ownership.  The ASF licenses this file
     to you under the Apache License, Version 2.0 (the
     "License"); you may not use this file except in compliance
     with the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing,
     software distributed under the License is distributed on an
     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
     KIND, either express or implied.  See the License for the
     specific language governing permissions and limitations
     under the License.
////
= Apache NetBeans source and daily builds
:jbake-type: page
:jbake-tags: 
:jbake-status: published
:keywords: Apache NetBeans source and daily builds
:icons: font
:description: Apache NetBeans source and daily builds

All Apache NetBeans source code is freely available to build yourself, or you can
download (unsupported) daily development builds.

== Daily builds

Please visit link:https://ci-builds.apache.org/job/Netbeans/job/netbeans-linux/[https://ci-builds.apache.org/job/Netbeans/job/netbeans-linux/] for the daily builds.

== Building from source

You can of course build Apache NetBeans from source. To do so:

. Clone the link:https://github.com/apache/netbeans[https://github.com/apache/netbeans] GitHub repository.
. Install an LTS release of the Java Development Kit.
. Install Apache Ant 1.10 or greater (link:https://ant.apache.org/[https://ant.apache.org/]).
. Set JAVA_HOME and ANT_HOME appropriately or leave them undefined.

Once you're all set, enter the `netbeans` directory:

- To build the Apache NetBeans IDE, according to the JDK:
  ** On JDK 8, type `ant build`
  ** On JDK 9 or later, type `ant build -Dpermit.jdk9.builds=true`
- The build will generate a binary zip bundle of the IDE at `./nbbuild/NetBeans-<version-hash>-release.zip`, and you can:
  ** Extract that zip in a place of your choosing and run `netbeans/bin/netbeans` (or `netbeans/bin/netbeans.exe` on Windows).
  ** Type `ant tryme` to run the Apache NetBeans IDE directly from the build folder rather than the zip for development purposes.

For details, go here: link:https://cwiki.apache.org/confluence/display/NETBEANS/Development+Environment[https://cwiki.apache.org/confluence/display/NETBEANS/Development+Environment]

Now that you have built Apache NetBeans from source you may want to xref:../../participate/submit-pr.adoc[submit a pull request].

=== Repositories

This is a list of Apache NetBeans repositories:

- link:https://github.com/apache/netbeans[https://github.com/apache/netbeans] The main source code repository.
- link:https://github.com/apache/netbeans-l10n[https://github.com/apache/netbeans-l10n] Translation bundle repository.
- link:https://github.com/apache/netbeans-website[https://github.com/apache/netbeans-website] This website's repository.
- link:https://github.com/apache/netbeans-website-cleanup[https://github.com/apache/netbeans-website-cleanup] A repository used to clean up existing documentation from pass:[http://netbeans.org]
- link:https://github.com/apache/netbeans-tools[https://github.com/apache/netbeans-tools] Tools and facilities in support of the Apache NetBeans project.
- Emilian Bold has converted the previous Mercurial repository (pass:[http://hg.netbeans.org]) to git, for historical reference, and has kindly uploaded it to GitHub at https://github.com/emilianbold/netbeans-releases. Thanks, Emilian!





