// 
//     Licensed to the Apache Software Foundation (ASF) under one
//     or more contributor license agreements.  See the NOTICE file
//     distributed with this work for additional information
//     regarding copyright ownership.  The ASF licenses this file
//     to you under the Apache License, Version 2.0 (the
//     "License"); you may not use this file except in compliance
//     with the License.  You may obtain a copy of the License at
// 
//       http://www.apache.org/licenses/LICENSE-2.0
// 
//     Unless required by applicable law or agreed to in writing,
//     software distributed under the License is distributed on an
//     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
//     KIND, either express or implied.  See the License for the
//     specific language governing permissions and limitations
//     under the License.
//


= Backward Compatibility Testing of NetBeans Platform
:jbake-type: wiki
:jbake-tags: wiki, devfaq, needsreview
:jbake-status: published
:syntax: true
:description: Backward Compatibility Testing of NetBeans Platform
:icons: font
:source-highlighter: pygments
:toc: left
:toc-title:
:experimental:

We want to assure the backward compatibility of NetBeans Platform/IDE.


[[What_is_backward_compatibility]]
== What is backward compatibility

The goal when producing new version of NetBeans Platform is to be backward compatible, unless otherwise stated. This means that if you developed a module/plugin for version A of the platform then it should work even in platform version B that was developed a few years later. If there is a module for which the previous statement is not true, then the
compatibility is compromised. Discovering such modules is generally bad sign. It can either mean that there is an unwanted incompatible change, and in such case we shall fix it prior to release, or this change is desirable and highly justified, and in such case it should be properly documented. In either case, backward compatibility is the strongest commitment of the NetBeans platform. Undesired incompatible changes have to be eliminated.


[[How_can_you_help]]
== How can you help

If you develop a module for NB IDE or an application based on NB Platform then it is in your own interest to know if your module works with the newer version of IDE/Platform. You can xref:BackwardCompatibilityTesting.adoc#How_to_test[test the backward compatibility] by yourself and let us know the result of your testing. We will evaluate your results and report bugs to the developers. Or you can report the bugs by yourself.

There are multiple levels of compatibility. Ability to compile old code against new version. Ability to link old binaries with new version and last, but definitely not least, ability to guarantee that behavior of NetBeans libraries remains unchanged. That is the highest level of compatibility.


[[How_to_test]]
== How to test


[[Modules_for_NetBeans_IDE]]
=== Modules for NetBeans IDE



1. install the module to newer version of IDE. E.g. module was developed for NB 6.0 (previous version). Install it to NB 6.1 (next version).
* module have to install correctly -> no exceptions/no warning/no missing dependencies etc.
. test module functionality
* it should work without any unexpected exceptions

[[Application_based_on_NB_RCP]]
=== Application based on NB RCP



1. install the application
. replace the RCP with newer (next) version -> replace platformX directory in the platformX+1 from the latest version of IDE
. start your application
* the application works correctly
* your tests pass 
* If not sent us the results of your test or write down what was wrong


[[How_to_join]]
== How to join

* Wait for a message "Backward Compatibility Testing Call for NB VERSION" on nbdev@netbeans.org
* Test your module/application with NB VERSION of NetBeans

* test the functionality with automated tests or manually
* Let us know the results at compatibility@platform.netbeans.org 

* the e-mail *must* contain:


1. brief module/application description - we don't want to test the module/app by ourself however we would like to know what it is doing
. platform/IDE version that the application/module was created on/for
. test results - summary of passed/failed tests is enough 
. bug numbers (if you filled any)
* we will contact you back if we will need a more informations


[[For_late_comer_or_people_that_have_problem_with_deadlines]]
== For late comer or people that have problem with deadlines

* Fell free to mail us results of your backward compatibility testing anytime
* Fill bugs about your problems



[NOTE]
====

The content in this page was kindly donated by Oracle Corp. to the
Apache Software Foundation.

This page was exported from link:http://wiki.netbeans.org/BackwardCompatibilityTesting[http://wiki.netbeans.org/BackwardCompatibilityTesting] , 
that was last modified by NetBeans user Admin 
on 2009-11-04T20:54:25Z.

This document was automatically converted to the AsciiDoc format on 2020-03-15, and needs to be reviewed.
====
