// 
//     Licensed to the Apache Software Foundation (ASF) under one
//     or more contributor license agreements.  See the NOTICE file
//     distributed with this work for additional information
//     regarding copyright ownership.  The ASF licenses this file
//     to you under the Apache License, Version 2.0 (the
//     "License"); you may not use this file except in compliance
//     with the License.  You may obtain a copy of the License at
// 
//       http://www.apache.org/licenses/LICENSE-2.0
// 
//     Unless required by applicable law or agreed to in writing,
//     software distributed under the License is distributed on an
//     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
//     KIND, either express or implied.  See the License for the
//     specific language governing permissions and limitations
//     under the License.
//

= DevFaqFileObjectInMemory
:jbake-type: wiki
:jbake-tags: wiki, devfaq, needsreview
:jbake-status: published
:keywords: Apache NetBeans wiki DevFaqFileObjectInMemory
:description: Apache NetBeans wiki DevFaqFileObjectInMemory
:toc: left
:toc-title:
:syntax: true

== How can I create a FileObject in memory?

Sometimes it's desirable to work with a file (or call code that expects to operate on files), but you don't want to commit it permanently to disk.  It's easy to do this in NetBeans by using the in-memory filesystem.  The first two lines in the following code will create a new text file and the next three will open it in an editor.  You can easily change this to handle other types of files provided that their DataObject's also have an OpenCookie.

[source,java]
----

    FileSystem fs = FileUtil.createMemoryFileSystem();
    FileObject fob = fs.getRoot().createData(name, "txt");

    DataObject data = DataObject.find(fob);
    OpenCookie cookie = (OpenCookie)data.getCookie(OpenCookie.class);
    cookie.open();

----

=== Apache Migration Information

The content in this page was kindly donated by Oracle Corp. to the
Apache Software Foundation.

This page was exported from link:http://wiki.netbeans.org/DevFaqFileObjectInMemory[http://wiki.netbeans.org/DevFaqFileObjectInMemory] , 
that was last modified by NetBeans user Jtulach 
on 2010-07-24T19:59:52Z.


*NOTE:* This document was automatically converted to the AsciiDoc format on 2018-02-07, and needs to be reviewed.
