// 
//     Licensed to the Apache Software Foundation (ASF) under one
//     or more contributor license agreements.  See the NOTICE file
//     distributed with this work for additional information
//     regarding copyright ownership.  The ASF licenses this file
//     to you under the Apache License, Version 2.0 (the
//     "License"); you may not use this file except in compliance
//     with the License.  You may obtain a copy of the License at
// 
//       http://www.apache.org/licenses/LICENSE-2.0
// 
//     Unless required by applicable law or agreed to in writing,
//     software distributed under the License is distributed on an
//     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
//     KIND, either express or implied.  See the License for the
//     specific language governing permissions and limitations
//     under the License.
//

= DevFaqGeneralWhatIsNetBeansExe
:jbake-type: wiki
:jbake-tags: wiki, devfaq, needsreview
:jbake-status: published
:keywords: Apache NetBeans wiki DevFaqGeneralWhatIsNetBeansExe
:description: Apache NetBeans wiki DevFaqGeneralWhatIsNetBeansExe
:toc: left
:toc-title:
:syntax: true

=== What is netbeans.exe, who compiles it and why is it there?

netbeans.exe is the Windows launcher for NetBeans.  Basically it assembles the class path string for starting up NetBeans, passes the command line arguments, etc., and launches Java with those arguments.

The main reasons for the exe are:

* Start NetBeans without a console window opening as well as the main window
* Windows shell quoting is inconsistent across versions of Windows
* On some versions of Windows, command line length is limited to a shorter length than is sometimes needed for all the command-line arguments that should be passed to java
* Provide a thing you can double click that has the correct icon

It's nothing terribly exciting, it's just a small C++ app;  the sources are in ide/launcher.

Up to NetBeans 6.5 there were actually two executables - nb.exe and netbeans.exe.  netbeans.exe will suppress the console window (so you won't see any logging on the command line);  nb.exe will show the command line.  Under the hood, netbeans.exe invokes nb.exe (so don't rename it).

Starting with NetBeans 6.7 the following changes in the Windows launcher were introduced - link:WinNB67Launcher.asciidoc[WinNB67Launcher].

=== Apache Migration Information

The content in this page was kindly donated by Oracle Corp. to the
Apache Software Foundation.

This page was exported from link:http://wiki.netbeans.org/DevFaqGeneralWhatIsNetBeansExe[http://wiki.netbeans.org/DevFaqGeneralWhatIsNetBeansExe] , 
that was last modified by NetBeans user Admin 
on 2009-11-06T15:45:08Z.


*NOTE:* This document was automatically converted to the AsciiDoc format on 2018-02-07, and needs to be reviewed.
