// 
//     Licensed to the Apache Software Foundation (ASF) under one
//     or more contributor license agreements.  See the NOTICE file
//     distributed with this work for additional information
//     regarding copyright ownership.  The ASF licenses this file
//     to you under the Apache License, Version 2.0 (the
//     "License"); you may not use this file except in compliance
//     with the License.  You may obtain a copy of the License at
// 
//       http://www.apache.org/licenses/LICENSE-2.0
// 
//     Unless required by applicable law or agreed to in writing,
//     software distributed under the License is distributed on an
//     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
//     KIND, either express or implied.  See the License for the
//     specific language governing permissions and limitations
//     under the License.
//

= DevFaqOpenReadOnly
:jbake-type: wiki
:jbake-tags: wiki, devfaq, needsreview
:jbake-status: published
:keywords: Apache NetBeans wiki DevFaqOpenReadOnly
:description: Apache NetBeans wiki DevFaqOpenReadOnly
:toc: left
:toc-title:
:syntax: true

=== How can I open a file in the editor in read-only mode?

You will need to make a special file editor which refuses to take a write lock:

[source,java]
----

public final class ROEditor extends DataEditorSupport {
    private ROEditor(DataObject d) {
        super(d, new E(d));
    }
    public ROEditor(FileObject fo) throws DataObjectNotFoundException {
        this(DataObject.find(fo));
    }
    private static final class E extends DataEditorSupport.Env {
        public E(DataObject d) {
            super(d);
        }
        protected FileObject getFile() {
            return getDataObject().getPrimaryFile();
        }
        protected FileLock takeLock() throws IOException {
            throw new IOException("No way!");
        }
    }
}
----

Demo of usage:

[source,java]
----

JFileChooser jfc = new JFileChooser();
if (jfc.showOpenDialog(null) != JFileChooser.APPROVE_OPTION) {
    return;
}
File f = jfc.getSelectedFile();
FileObject fo = FileUtil.toFileObject(f);
try {
    new ROEditor(fo).open();
} catch (DataObjectNotFoundException e) {
    e.printStackTrace();
}
----

Applies to: NetBeans 4.0 and newer

=== Apache Migration Information

The content in this page was kindly donated by Oracle Corp. to the
Apache Software Foundation.

This page was exported from link:http://wiki.netbeans.org/DevFaqOpenReadOnly[http://wiki.netbeans.org/DevFaqOpenReadOnly] , 
that was last modified by NetBeans user Vstejskal 
on 2010-06-16T13:28:46Z.


*NOTE:* This document was automatically converted to the AsciiDoc format on 2018-02-07, and needs to be reviewed.
