// 
//     Licensed to the Apache Software Foundation (ASF) under one
//     or more contributor license agreements.  See the NOTICE file
//     distributed with this work for additional information
//     regarding copyright ownership.  The ASF licenses this file
//     to you under the Apache License, Version 2.0 (the
//     "License"); you may not use this file except in compliance
//     with the License.  You may obtain a copy of the License at
// 
//       http://www.apache.org/licenses/LICENSE-2.0
// 
//     Unless required by applicable law or agreed to in writing,
//     software distributed under the License is distributed on an
//     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
//     KIND, either express or implied.  See the License for the
//     specific language governing permissions and limitations
//     under the License.
//

= DevFaqModulesLayerFile
:jbake-type: wiki
:jbake-tags: wiki, devfaq, needsreview
:jbake-status: published
:keywords: Apache NetBeans wiki DevFaqModulesLayerFile
:description: Apache NetBeans wiki DevFaqModulesLayerFile
:toc: left
:toc-title:
:syntax: true

=== What is a layer file, or "module layer"?

Layer files are small XML files provided by modules, which define a virtual filesystem (link:DevFaqFileSystem.asciidoc[DevFaqFileSystem]).
The layer file defines folders and files that will be merged into the system filesystem (link:DevFaqSystemFilesystem.asciidoc[DevFaqSystemFilesystem])
that makes up the runtime configuration information NetBeans and its modules use.

Layer files help to make it possible for modules to be dynamically installed.
If you've read about `FileObject`s (link:DevFaqFileObject.asciidoc[DevFaqFileObject])
and `FileSystem`s (link:DevFaqFileSystem.asciidoc[DevFaqFileSystem]),
you know that you can listen for changes in folders and files in a filesystem.
That's exactly what the components of NetBeans whose content is composed from folders in the system filesystem do.
So if a module is added at runtime, the system filesystem fires changes;
the UI notices that the contents of the folder has
changed and updates the UI to reflect the changes.

If you created your module using the IDE, you may already have an XML layer in your
module, and you can expand the node for it under *Important Files* in your module project to see and modify its contents.
The way it is declared is simple:

* In your JAR, provide the layer file - e.g. `com/foo/mymodule/resources/layer.xml`
* In your module's manifest, include the following line somewhere in the top section:
[source,java]
----

OpenIDE-Module-Layer: com/foo/mymodule/resources/layer.xml
----

Some Java source code annotations generate layer entries for you (you do not need to have a `layer.xml` in your module's source tree).

<hr/>
Applies to: NetBeans 6.7 and later

=== Apache Migration Information

The content in this page was kindly donated by Oracle Corp. to the
Apache Software Foundation.

This page was exported from link:http://wiki.netbeans.org/DevFaqModulesLayerFile[http://wiki.netbeans.org/DevFaqModulesLayerFile] , 
that was last modified by NetBeans user Jglick 
on 2010-06-14T22:16:01Z.


*NOTE:* This document was automatically converted to the AsciiDoc format on 2018-02-07, and needs to be reviewed.
