// 
//     Licensed to the Apache Software Foundation (ASF) under one
//     or more contributor license agreements.  See the NOTICE file
//     distributed with this work for additional information
//     regarding copyright ownership.  The ASF licenses this file
//     to you under the Apache License, Version 2.0 (the
//     "License"); you may not use this file except in compliance
//     with the License.  You may obtain a copy of the License at
// 
//       http://www.apache.org/licenses/LICENSE-2.0
// 
//     Unless required by applicable law or agreed to in writing,
//     software distributed under the License is distributed on an
//     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
//     KIND, either express or implied.  See the License for the
//     specific language governing permissions and limitations
//     under the License.
//

= DevFaqPropertySheetNodes
:jbake-type: wiki
:jbake-tags: wiki, devfaq, needsreview
:jbake-status: published
:keywords: Apache NetBeans wiki DevFaqPropertySheetNodes
:description: Apache NetBeans wiki DevFaqPropertySheetNodes
:toc: left
:toc-title:
:syntax: true

=== How do I show my node's properties in the Properties view?

I want to have the properties of my custom nodes displayed in the Properties view when they are selected in my tree view. How do I go about doing that?

Listen for changes in the selected nodes in the [link:http://bits.netbeans.org/dev/javadoc/org-openide-explorer/org/openide/explorer/ExplorerManager.html[http://bits.netbeans.org/dev/javadoc/org-openide-explorer/org/openide/explorer/ExplorerManager.html] `ExplorerManager`], and set the `activatedNodes` property on the parent [[DevFaqWindowsTopComponent| `TopComponent`]] which contains your tree view:

[source,java]
----

public class MyComponent extends TopComponent implements PropertyChangeListener {
    private ExplorerManager explorerManager;
----
[source,java]
----

    public MyComponent() {
        explorerManager = new ExplorerManager();
        explorerManager.addPropertyChangeListener(this);
    }
----
[source,java]
----

    public void propertyChange(PropertyChangeEvent evt) {
        if (evt.getSource() == explorerManager &&
                ExplorerManager.PROP_SELECTED_NODES.equals(evt.getPropertyName())) {
           setActivatedNodes(explorerManager.getSelectedNodes());
        }
    }
}
----

Note that the example above is not a complete `TopComponent` implementation with a tree view and nodes. It is simply demonstrating how to have the selected node's properties shown in the Properties view.

=== Apache Migration Information

The content in this page was kindly donated by Oracle Corp. to the
Apache Software Foundation.

This page was exported from link:http://wiki.netbeans.org/DevFaqPropertySheetNodes[http://wiki.netbeans.org/DevFaqPropertySheetNodes] , 
that was last modified by NetBeans user Tboudreau 
on 2010-02-25T16:17:19Z.


*NOTE:* This document was automatically converted to the AsciiDoc format on 2018-02-07, and needs to be reviewed.
