// 
//     Licensed to the Apache Software Foundation (ASF) under one
//     or more contributor license agreements.  See the NOTICE file
//     distributed with this work for additional information
//     regarding copyright ownership.  The ASF licenses this file
//     to you under the Apache License, Version 2.0 (the
//     "License"); you may not use this file except in compliance
//     with the License.  You may obtain a copy of the License at
// 
//       http://www.apache.org/licenses/LICENSE-2.0
// 
//     Unless required by applicable law or agreed to in writing,
//     software distributed under the License is distributed on an
//     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
//     KIND, either express or implied.  See the License for the
//     specific language governing permissions and limitations
//     under the License.
//

= DevFaqOpenFile
:jbake-type: wiki
:jbake-tags: wiki, devfaq, needsreview
:jbake-status: published
:keywords: Apache NetBeans wiki DevFaqOpenFile
:description: Apache NetBeans wiki DevFaqOpenFile
:toc: left
:toc-title:
:syntax: true

=== Approach 1

Answer from link:http://forums.netbeans.org/topic32140.html&highlight=[this] post:

[source,java]
----

FileObject fo = FileUtil.toFileObject(new File("test.js").getAbsoluteFile()); 
DataObject newDo = DataObject.find(fo); 
final Node node = newDo.getNodeDelegate(); 
Action a = node.getPreferredAction(); 
if (a instanceof ContextAwareAction) { 
       a = ((ContextAwareAction) a).createContextAwareInstance(node.getLookup()); 
} 
if (a != null) { 
      a.actionPerformed(new ActionEvent(node, ActionEvent.ACTION_PERFORMED, "")); // NOI18N 
}
----

Keep in mind that this must be called from the EDT thread, it'll raise a RuntimeException otherwise.

=== Approach 2

[source,java]
----

FileObject fileObject=...
DataObject.find(fileObject).getLookup().lookup(OpenCookie.class).open();
----

=== Apache Migration Information

The content in this page was kindly donated by Oracle Corp. to the
Apache Software Foundation.

This page was exported from link:http://wiki.netbeans.org/DevFaqOpenFile[http://wiki.netbeans.org/DevFaqOpenFile] , 
that was last modified by NetBeans user Markiewb 
on 2013-05-16T18:09:04Z.


*NOTE:* This document was automatically converted to the AsciiDoc format on 2018-02-07, and needs to be reviewed.
