// 
//     Licensed to the Apache Software Foundation (ASF) under one
//     or more contributor license agreements.  See the NOTICE file
//     distributed with this work for additional information
//     regarding copyright ownership.  The ASF licenses this file
//     to you under the Apache License, Version 2.0 (the
//     "License"); you may not use this file except in compliance
//     with the License.  You may obtain a copy of the License at
// 
//       http://www.apache.org/licenses/LICENSE-2.0
// 
//     Unless required by applicable law or agreed to in writing,
//     software distributed under the License is distributed on an
//     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
//     KIND, either express or implied.  See the License for the
//     specific language governing permissions and limitations
//     under the License.
//

= DevFaqJSeparatorInMainToolbar
:jbake-type: wiki
:jbake-tags: wiki, devfaq, needsreview
:jbake-status: published
:keywords: Apache NetBeans wiki DevFaqJSeparatorInMainToolbar
:description: Apache NetBeans wiki DevFaqJSeparatorInMainToolbar
:toc: left
:toc-title:
:syntax: true

=== How can I add a JSeparator to the main toolbar?

It's easy to add a separator to the menus by editing the module's layer file; in fact, the Action wizard will do this for you.  Items in the main toolbar are also configured through the layer file, but you may find that adding a separator as you would for the menu does not work in the toolbar.  So how do you add a separator to the toolbar?

You can do this by creating a class like:

[source,java]
----

package com.example.util.widgets;

public class VerticalSeparator extends JSeparator {
	
    public VerticalSeparator() {
        super(JSeparator.VERTICAL);
    }

    @Override
    public Dimension getMaximumSize() {
        return new Dimension(getPreferredSize().width, super.getMaximumSize().height);
    }

    @Override
    public Dimension getSize() {
        return new Dimension(getPreferredSize().width, super.getSize().height);
    }
}

----

Then simply reference an instance of this separator in the layer file:

[source,xml]
----

<file name="SeparatorAfterModelToolbarActions.instance">
    <attr name="instanceClass" stringvalue="com.example.util.widgets.VerticalSeparator"/>
    <attr name="position" intvalue="25"/>
</file>

----

=== Apache Migration Information

The content in this page was kindly donated by Oracle Corp. to the
Apache Software Foundation.

This page was exported from link:http://wiki.netbeans.org/DevFaqJSeparatorInMainToolbar[http://wiki.netbeans.org/DevFaqJSeparatorInMainToolbar] , 
that was last modified by NetBeans user Jtulach 
on 2010-07-24T20:37:58Z.


*NOTE:* This document was automatically converted to the AsciiDoc format on 2018-02-07, and needs to be reviewed.
