// 
//     Licensed to the Apache Software Foundation (ASF) under one
//     or more contributor license agreements.  See the NOTICE file
//     distributed with this work for additional information
//     regarding copyright ownership.  The ASF licenses this file
//     to you under the Apache License, Version 2.0 (the
//     "License"); you may not use this file except in compliance
//     with the License.  You may obtain a copy of the License at
// 
//       http://www.apache.org/licenses/LICENSE-2.0
// 
//     Unless required by applicable law or agreed to in writing,
//     software distributed under the License is distributed on an
//     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
//     KIND, either express or implied.  See the License for the
//     specific language governing permissions and limitations
//     under the License.
//

= DevFaqLogicalKeybindings
:jbake-type: wiki
:jbake-tags: wiki, devfaq, needsreview
:jbake-status: published
:keywords: Apache NetBeans wiki DevFaqLogicalKeybindings
:description: Apache NetBeans wiki DevFaqLogicalKeybindings
:toc: left
:toc-title:
:syntax: true

=== Why should I use D- for Ctrl and O- for Alt - I thought C stood for Ctrl and A stood for alt?

(Wondering what this is about?  See the link:DevFaqKeybindings.asciidoc[general FAQ item on keybindings]).

There should be *no* Alt-bound keyboard shortcuts on Macintosh, _ever_ - it is used on international keyboards as the compose key (for a long time, we didn't know it, but Norwegian and French users could not type } or { in NetBeans - kind of limits the usefuless of a Java IDE).

All standard shortcuts should be bound with wildcard keys - e.g., in the layer, not AS-P for Alt-Shift-P, but OS-P, which will map to Alt-Shift-P on PC and Ctrl-Shift-P on mac.  For Ctrl/Command, in the layer put DS-P instead of CS-P to bind conditionally to ctrl on PC and command on mac.

All Alt-bound keybindings in the IDE are specified with O so that they are rebound to Ctrl on mac, because they will interfere with typing in a lot of locales (the real way to think about it is "the mac does not have an Alt key" - it does but it is a composition key - you can't use it).

Any alt-bound keybinding on mac is a bug.  If you use the logical syntax for keybindings, your app will always work intuitively on any platform.

Note that the mapping handling does skip key combinations that simply can't work on Mac - for example, Command-H and Command-Q are always consumed by the OS, so D-H and D-Q map to Ctrl-H and Ctrl-Q, respectively, everywhere.

=== Apache Migration Information

The content in this page was kindly donated by Oracle Corp. to the
Apache Software Foundation.

This page was exported from link:http://wiki.netbeans.org/DevFaqLogicalKeybindings[http://wiki.netbeans.org/DevFaqLogicalKeybindings] , 
that was last modified by NetBeans user Tboudreau 
on 2010-02-24T21:17:52Z.


*NOTE:* This document was automatically converted to the AsciiDoc format on 2018-02-07, and needs to be reviewed.
