// 
//     Licensed to the Apache Software Foundation (ASF) under one
//     or more contributor license agreements.  See the NOTICE file
//     distributed with this work for additional information
//     regarding copyright ownership.  The ASF licenses this file
//     to you under the Apache License, Version 2.0 (the
//     "License"); you may not use this file except in compliance
//     with the License.  You may obtain a copy of the License at
// 
//       http://www.apache.org/licenses/LICENSE-2.0
// 
//     Unless required by applicable law or agreed to in writing,
//     software distributed under the License is distributed on an
//     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
//     KIND, either express or implied.  See the License for the
//     specific language governing permissions and limitations
//     under the License.
//

= DevFaqGlobalVsEditorKeybindings
:jbake-type: wiki
:jbake-tags: wiki, devfaq, needsreview
:jbake-status: published
:keywords: Apache NetBeans wiki DevFaqGlobalVsEditorKeybindings
:description: Apache NetBeans wiki DevFaqGlobalVsEditorKeybindings
:toc: left
:toc-title:
:syntax: true

=== What are editor-specific keybindings and how are they different from global ones?

The editor has its own mechanism for registering keybindings, which is separate from global keybindings (in essence, they belong to the Swing EditorKit for the editor, but there are some registration mechanisms in the editor for this).  So if you want to register a keyboard shortcut only against the editor when editing a certain type of file (as opposed to a keyboard shortcut that is a shortcut for an action on the main menu), you'll be using editor-based keybindings.

If there is a global shortcut bound to a key combination, and also an editor-specific one defined for the type of file being edited, the editor wins if the editor has focus.

=== Apache Migration Information

The content in this page was kindly donated by Oracle Corp. to the
Apache Software Foundation.

This page was exported from link:http://wiki.netbeans.org/DevFaqGlobalVsEditorKeybindings[http://wiki.netbeans.org/DevFaqGlobalVsEditorKeybindings] , 
that was last modified by NetBeans user Admin 
on 2009-11-06T15:45:34Z.


*NOTE:* This document was automatically converted to the AsciiDoc format on 2018-02-07, and needs to be reviewed.
