// 
//     Licensed to the Apache Software Foundation (ASF) under one
//     or more contributor license agreements.  See the NOTICE file
//     distributed with this work for additional information
//     regarding copyright ownership.  The ASF licenses this file
//     to you under the Apache License, Version 2.0 (the
//     "License"); you may not use this file except in compliance
//     with the License.  You may obtain a copy of the License at
// 
//       http://www.apache.org/licenses/LICENSE-2.0
// 
//     Unless required by applicable law or agreed to in writing,
//     software distributed under the License is distributed on an
//     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
//     KIND, either express or implied.  See the License for the
//     specific language governing permissions and limitations
//     under the License.
//

= DevFaqFilesystemSee
:jbake-type: wiki
:jbake-tags: wiki, devfaq, needsreview
:jbake-status: published
:keywords: Apache NetBeans wiki DevFaqFilesystemSee
:description: Apache NetBeans wiki DevFaqFilesystemSee
:toc: left
:toc-title:
:syntax: true

=== How can I see the system filesystem (`FileUtil.getConfigRoot()`)?

The layer file browser in NetBeans project support shows the default file system.

Open a NetBeans module project in the Projects window. Navigate to *Important Files* > *XML Layer* > *<this layer in context>*. You can examine the IDE's default file system by browsing the *<this layer in context>* node. 

While browsing the filesystem remember that each node has a "Name" property (use the Properties Window to see the properties of each node). You must use the "Name" to refer to the node in the filesystem.

For instance, in default (English) locale the menu bar appears as the node *Menu Bar* in the filesystem viewer, but its nonlocalizable code name is *Menu*. So to refer to the menu bar
in your `layer.xml` file you have to use the name of the node, like this:

[source,java]
----

<folder name="Menu">
----

instead of

[source,java]
----

<folder name="Menu Bar">
----

-

Applies to: NetBeans 6.7 and later

=== Apache Migration Information

The content in this page was kindly donated by Oracle Corp. to the
Apache Software Foundation.

This page was exported from link:http://wiki.netbeans.org/DevFaqFilesystemSee[http://wiki.netbeans.org/DevFaqFilesystemSee] , 
that was last modified by NetBeans user Jglick 
on 2009-12-03T13:53:09Z.


*NOTE:* This document was automatically converted to the AsciiDoc format on 2018-02-07, and needs to be reviewed.
