// 
//     Licensed to the Apache Software Foundation (ASF) under one
//     or more contributor license agreements.  See the NOTICE file
//     distributed with this work for additional information
//     regarding copyright ownership.  The ASF licenses this file
//     to you under the Apache License, Version 2.0 (the
//     "License"); you may not use this file except in compliance
//     with the License.  You may obtain a copy of the License at
// 
//       http://www.apache.org/licenses/LICENSE-2.0
// 
//     Unless required by applicable law or agreed to in writing,
//     software distributed under the License is distributed on an
//     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
//     KIND, either express or implied.  See the License for the
//     specific language governing permissions and limitations
//     under the License.
//

= DevFaqActionAddAnyFolder
:jbake-type: wiki
:jbake-tags: wiki, devfaq, needsreview
:jbake-status: published
:keywords: Apache NetBeans wiki DevFaqActionAddAnyFolder
:description: Apache NetBeans wiki DevFaqActionAddAnyFolder
:toc: left
:toc-title:
:syntax: true

=== How can I add actions to all folder nodes?

Register to *Loaders/folder/any/Actions*


Example:

[source,java]
----

@ActionID(
        category = "Build",
        id = "com.foo.bar.OnAnyFolderAction")
@ActionRegistration(
        displayName = "#CTL_OnAnyFolderAction")
@ActionReferences({
    @ActionReference(path = "Loaders/folder/any/Actions", position = 0)
})
@Messages("CTL_OnAnyFolderAction=ActionOnAnyFolder")
public final class OnAnyFolderAction implements ActionListener {

    private final DataFolder context;

    public OnAnyFolderAction(DataFolder context) {
        this.context = context;
    }

    @Override
    public void actionPerformed(ActionEvent ev) {
        JOptionPane.showMessageDialog(null, context.toString());
    }
}
----

=== Apache Migration Information

The content in this page was kindly donated by Oracle Corp. to the
Apache Software Foundation.

This page was exported from link:http://wiki.netbeans.org/DevFaqActionAddAnyFolder[http://wiki.netbeans.org/DevFaqActionAddAnyFolder] , 
that was last modified by NetBeans user Markiewb 
on 2013-07-07T19:41:45Z.


*NOTE:* This document was automatically converted to the AsciiDoc format on 2018-02-07, and needs to be reviewed.
