// 
//     Licensed to the Apache Software Foundation (ASF) under one
//     or more contributor license agreements.  See the NOTICE file
//     distributed with this work for additional information
//     regarding copyright ownership.  The ASF licenses this file
//     to you under the Apache License, Version 2.0 (the
//     "License"); you may not use this file except in compliance
//     with the License.  You may obtain a copy of the License at
// 
//       http://www.apache.org/licenses/LICENSE-2.0
// 
//     Unless required by applicable law or agreed to in writing,
//     software distributed under the License is distributed on an
//     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
//     KIND, either express or implied.  See the License for the
//     specific language governing permissions and limitations
//     under the License.
//

= DevFaqCutCopyPaste
:jbake-type: wiki
:jbake-tags: wiki, devfaq, needsreview
:jbake-status: published
:keywords: Apache NetBeans wiki DevFaqCutCopyPaste
:description: Apache NetBeans wiki DevFaqCutCopyPaste
:toc: left
:toc-title:
:syntax: true

=== How do I handle cut, copy and paste?

The subject of properly handling cut, copy and paste is underdocumented in modern material on the NetBeans Platform and I am not aware of any clear and concise examples that show how to handle all aspects of these common actions.  Anyone who can improve these shortcomings would be doing a great service for the NetBeans Platform developer community.

The link:http://bits.netbeans.org/dev/javadoc/org-openide-nodes/org/openide/nodes/doc-files/api.html#edit[Nodes API documentation] provides some guidance, while chapter 14 of _NetBeans: The Definitive Guide_ link:http://www.netbeans.org/download/books/definitive-guide/html/apis-c_betterexplorer.html#N400551[goes into greater detail].  Although some parts of _NetBeans: The Definitive Guide_ are now outdated, the portions related to the Nodes API are likely still relevant.

=== Apache Migration Information

The content in this page was kindly donated by Oracle Corp. to the
Apache Software Foundation.

This page was exported from link:http://wiki.netbeans.org/DevFaqCutCopyPaste[http://wiki.netbeans.org/DevFaqCutCopyPaste] , 
that was last modified by NetBeans user Jglick 
on 2010-05-04T13:46:11Z.


*NOTE:* This document was automatically converted to the AsciiDoc format on 2018-02-07, and needs to be reviewed.
