// 
//     Licensed to the Apache Software Foundation (ASF) under one
//     or more contributor license agreements.  See the NOTICE file
//     distributed with this work for additional information
//     regarding copyright ownership.  The ASF licenses this file
//     to you under the Apache License, Version 2.0 (the
//     "License"); you may not use this file except in compliance
//     with the License.  You may obtain a copy of the License at
// 
//       http://www.apache.org/licenses/LICENSE-2.0
// 
//     Unless required by applicable law or agreed to in writing,
//     software distributed under the License is distributed on an
//     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
//     KIND, either express or implied.  See the License for the
//     specific language governing permissions and limitations
//     under the License.
//

= DevFaqFindLocationInSourcesFromUi
:jbake-type: wiki
:jbake-tags: wiki, devfaq, needsreview
:jbake-status: published
:keywords: Apache NetBeans wiki DevFaqFindLocationInSourcesFromUi
:description: Apache NetBeans wiki DevFaqFindLocationInSourcesFromUi
:toc: left
:toc-title:
:syntax: true

==== Looking at the UI how do I find a module that implements a menu item?

Looking at text in IDE such as a menu item, window title, node display name, etc. you may want to change it. But first you need to find where in the code this string is produced. It is very easy to find if you add the following switch into your `.../etc/netbeans.conf`:

[source,java]
----

-J-Dorg.openide.util.NbBundle.DEBUG=true
----

If you use this switch all strings loaded from `Bundle.properties` files using `org.openide.util.NbBundle` will have two numbers appended to them. The first number identifies the bundle file. Look for this number in the IDE log to find the location of the properties file that provides this string.

Another handy trick: in a built source tree, run

[source,java]
----

ant index-layer-paths
----

to see which module (by code name) contributes each layer file (or folder),
including menu items and so on.
You can also just look at the trunk version of this file
link:http://deadlock.netbeans.org/hudson/job/nbms-and-javadoc/lastStableBuild/artifact/nbbuild/build/generated/layers.txt[here].

=== Apache Migration Information

The content in this page was kindly donated by Oracle Corp. to the
Apache Software Foundation.

This page was exported from link:http://wiki.netbeans.org/DevFaqFindLocationInSourcesFromUi[http://wiki.netbeans.org/DevFaqFindLocationInSourcesFromUi] , 
that was last modified by NetBeans user Admin 
on 2009-11-06T15:44:35Z.


*NOTE:* This document was automatically converted to the AsciiDoc format on 2018-02-07, and needs to be reviewed.
