// 
//     Licensed to the Apache Software Foundation (ASF) under one
//     or more contributor license agreements.  See the NOTICE file
//     distributed with this work for additional information
//     regarding copyright ownership.  The ASF licenses this file
//     to you under the Apache License, Version 2.0 (the
//     "License"); you may not use this file except in compliance
//     with the License.  You may obtain a copy of the License at
// 
//       http://www.apache.org/licenses/LICENSE-2.0
// 
//     Unless required by applicable law or agreed to in writing,
//     software distributed under the License is distributed on an
//     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
//     KIND, either express or implied.  See the License for the
//     specific language governing permissions and limitations
//     under the License.
//

= DevFaqHideRemoveToolbarMenu
:jbake-type: wiki
:jbake-tags: wiki, devfaq, needsreview
:jbake-status: published
:keywords: Apache NetBeans wiki DevFaqHideRemoveToolbarMenu
:description: Apache NetBeans wiki DevFaqHideRemoveToolbarMenu
:toc: left
:toc-title:
:syntax: true

== How do I hide/remove default toolbar buttons and/or menu items?

Create a layer.xml file in a NetBeans module (in the New File wizard, choose Module Development | XML Layer). Once you have created the layer.xml file, expand it in the Important Files node, find the item you want to remove, right-click on it, choose Delete. The _hidden tag for the layer folder or file will be added to your layer.xml file.

Alternatively, if you know the applicable names of folders or files, add the information to the layer.xml file yourself, e.g:

[source,xml]
----

<folder name="Menu">
    <folder name="File">
        <file name="org-netbeans-modules-project-ui-NewFile.shadow_hidden"/>
    </folder>
</folder>

----

=== Apache Migration Information

The content in this page was kindly donated by Oracle Corp. to the
Apache Software Foundation.

This page was exported from link:http://wiki.netbeans.org/DevFaqHideRemoveToolbarMenu[http://wiki.netbeans.org/DevFaqHideRemoveToolbarMenu] , 
that was last modified by NetBeans user Geertjan 
on 2016-01-06T16:58:05Z.


*NOTE:* This document was automatically converted to the AsciiDoc format on 2018-02-07, and needs to be reviewed.
