// 
//     Licensed to the Apache Software Foundation (ASF) under one
//     or more contributor license agreements.  See the NOTICE file
//     distributed with this work for additional information
//     regarding copyright ownership.  The ASF licenses this file
//     to you under the Apache License, Version 2.0 (the
//     "License"); you may not use this file except in compliance
//     with the License.  You may obtain a copy of the License at
// 
//       http://www.apache.org/licenses/LICENSE-2.0
// 
//     Unless required by applicable law or agreed to in writing,
//     software distributed under the License is distributed on an
//     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
//     KIND, either express or implied.  See the License for the
//     specific language governing permissions and limitations
//     under the License.
//

= DevFaqTemplatesInNonIdeApp
:jbake-type: wiki
:jbake-tags: wiki, devfaq, needsreview
:jbake-status: published
:keywords: Apache NetBeans wiki DevFaqTemplatesInNonIdeApp
:description: Apache NetBeans wiki DevFaqTemplatesInNonIdeApp
:toc: left
:toc-title:
:syntax: true

=== I am creating a non-IDE application.  How do I enable/control templates?

If the projectui module is installed, templates are only made available inside projects.

If you want to enable templates outside of a project (like folder is, by default), then you need to remove the projectui module but make sure the favorites (org.netbeans.modules.favorites) module is enabled for your suite.

To make your template available as one of the choices on the New File context menu (as opposed to having to choose the type in the wizard), then you have to list it as a privileged template.

See Tom Wheeler's  link:http://www.tomwheeler.com/netbeans/[TodoListManager] for an example of code that does these things.

=== Apache Migration Information

The content in this page was kindly donated by Oracle Corp. to the
Apache Software Foundation.

This page was exported from link:http://wiki.netbeans.org/DevFaqTemplatesInNonIdeApp[http://wiki.netbeans.org/DevFaqTemplatesInNonIdeApp] , 
that was last modified by NetBeans user Admin 
on 2009-11-06T16:01:57Z.


*NOTE:* This document was automatically converted to the AsciiDoc format on 2018-02-07, and needs to be reviewed.
