// 
//     Licensed to the Apache Software Foundation (ASF) under one
//     or more contributor license agreements.  See the NOTICE file
//     distributed with this work for additional information
//     regarding copyright ownership.  The ASF licenses this file
//     to you under the Apache License, Version 2.0 (the
//     "License"); you may not use this file except in compliance
//     with the License.  You may obtain a copy of the License at
// 
//       http://www.apache.org/licenses/LICENSE-2.0
// 
//     Unless required by applicable law or agreed to in writing,
//     software distributed under the License is distributed on an
//     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
//     KIND, either express or implied.  See the License for the
//     specific language governing permissions and limitations
//     under the License.
//

= FaqWhyTheCA
:jbake-type: wiki
:jbake-tags: wiki, devfaq, needsreview
:jbake-status: published
:keywords: Apache NetBeans wiki FaqWhyTheCA
:description: Apache NetBeans wiki FaqWhyTheCA
:toc: left
:toc-title:
:syntax: true

=== Why does NetBeans request a CA?

Oracle asks that you share the copyright on your contributions the first time you contribute code to netbeans.org, so that Oracle can protect the NetBeans code base and also allow consideration of alternative licensing models under a unified copyright for the netbeans.org code base.

Most importantly, having joint ownership of copyright allows Oracle to offer commercial, binary distributions of the NetBeans project. Without this ability, it would not be possible for Oracle to open its technologies, nor feasible to continue to invest in them as a business and employ developers working on the code.

See policy statement for more details at link:http://www.oracle.com/technetwork/oca-faq-405384.pdf[http://www.oracle.com/technetwork/oca-faq-405384.pdf]

=== Apache Migration Information

The content in this page was kindly donated by Oracle Corp. to the
Apache Software Foundation.

This page was exported from link:http://wiki.netbeans.org/FaqWhyTheCA[http://wiki.netbeans.org/FaqWhyTheCA] , 
that was last modified by NetBeans user Jkovalsky 
on 2011-12-12T14:38:30Z.


*NOTE:* This document was automatically converted to the AsciiDoc format on 2018-02-07, and needs to be reviewed.
