// 
//     Licensed to the Apache Software Foundation (ASF) under one
//     or more contributor license agreements.  See the NOTICE file
//     distributed with this work for additional information
//     regarding copyright ownership.  The ASF licenses this file
//     to you under the Apache License, Version 2.0 (the
//     "License"); you may not use this file except in compliance
//     with the License.  You may obtain a copy of the License at
// 
//       http://www.apache.org/licenses/LICENSE-2.0
// 
//     Unless required by applicable law or agreed to in writing,
//     software distributed under the License is distributed on an
//     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
//     KIND, either express or implied.  See the License for the
//     specific language governing permissions and limitations
//     under the License.
//

= HTTP Proxy Basic Authentication
:jbake-type: wiki
:jbake-tags: wiki, devfaq, needsreview
:jbake-status: published
:syntax: true
:description: APITest SIGTest NetBeans
:icons: font
:source-highlighter: pygments
:toc: left
:toc-title:
:experimental:

JDK 8u111 link:https://www.oracle.com/java/technologies/javase/8u111-relnotes.html[disabled Basic authentication for HTTPS tunneling], 
this means that if you use a network proxy with Apache NetBeans and this proxy is using Basic authentication you won't be able to
access HTTPS based servers.

As a workaround for this JDK feature, you can add the option 

[source]
----
-Djdk.http.auth.tunneling.disabledSchemes="" 
----

to the Apache NetBeans `etc/netbeans.conf` configuration file, in the `netbeans_default_options` entry, like so:

[source]
----
netbeans_default_options="-J-XX:+UseStringDeduplication -J-Xss2m -J-Djdk.http.auth.tunneling.disabledSchemes=\"\" -J-Dapple.laf.useScreenMenuBar=true (...)
----

NOTE: We don't want to set this as a default options because it may pose a security problem.

NOTE: This was reported as link:https://github.com/apache/netbeans/issues/3748[issue #3748] in github.




