////
     Licensed to the Apache Software Foundation (ASF) under one
     or more contributor license agreements.  See the NOTICE file
     distributed with this work for additional information
     regarding copyright ownership.  The ASF licenses this file
     to you under the Apache License, Version 2.0 (the
     "License"); you may not use this file except in compliance
     with the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing,
     software distributed under the License is distributed on an
     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
     KIND, either express or implied.  See the License for the
     specific language governing permissions and limitations
     under the License.
////
////

NOTE: 
See https://www.apache.org/dev/release-download-pages.html 
for important requirements for download pages for Apache projects.

////
= Downloading Apache NetBeans (incubating) 10.0 
:jbake-type: page
:jbake-tags: download
:jbake-status: published
:keywords: Apache NetBeans 10.0 Download
:description: Apache NetBeans 10.0 Download
:toc: left
:toc-title:

Apache NetBeans (incubating) 10.0 was announced on the 27th of December, 2018.
See xref:index.adoc[Apache NetBeans 10.0 Features] for a full list of features.

////
NOTE: It's mandatory to link to the source. It's optional to link to the binaries.
NOTE: It's mandatory to link against https://www.apache.org for the sums & keys. https is recommended.
NOTE: It's NOT recommended to link to github.
////
Apache NetBeans 10.0 is available for download from your closest Apache mirror. For this release no official installers are provided, please just download the binaries and unzip them.

- Source: link:https://archive.apache.org/dist/incubator/netbeans/incubating-netbeans/incubating-10.0/incubating-netbeans-10.0-source.zip[incubating-netbeans-10.0-source.zip] 
(link:https://archive.apache.org/dist/incubator/netbeans/incubating-netbeans/incubating-10.0/incubating-netbeans-10.0-source.zip.sha512[SHA-512],
link:https://archive.apache.org/dist/incubator/netbeans/incubating-netbeans/incubating-10.0/incubating-netbeans-10.0-source.zip.asc[PGP ASC])

- Binaries: 
link:https://archive.apache.org/dist/incubator/netbeans/incubating-netbeans/incubating-10.0/incubating-netbeans-10.0-bin.zip[incubating-netbeans-10.0-bin.zip] (
link:https://archive.apache.org/dist/incubator/netbeans/incubating-netbeans/incubating-10.0/incubating-netbeans-10.0-bin.zip.sha512[SHA-512],
link:https://archive.apache.org/dist/incubator/netbeans/incubating-netbeans/incubating-10.0/incubating-netbeans-10.0-bin.zip.asc[PGP ASC])

- Javadoc for this release is available at https://bits.netbeans.org/10.0/javadoc

////
NOTE: Using https below is highly recommended.
////
Officially, it is important that you link:https://www.apache.org/dyn/closer.cgi#verify[verify the integrity] of the downloaded files using the PGP signatures (.asc file) or a hash (.sha512 files).  The PGP keys used to sign this release are available link:https://dist.apache.org/repos/dist/release/incubator/netbeans/KEYS[here].

Also see the following YouTube clip:

video::O8cwpEY1OAQ[youtube, title="The Rough Guide to Apache NetBeans 10"]

== Building from source

To build Apache NetBeans (incubating) 10.0 from source you need:

. Oracle's Java 8 or Open JDK v8.
. Apache Ant 1.10 or greater (link:https://ant.apache.org[https://ant.apache.org]).

Once you have everything installed then:

1. Unzip link:https://archive.apache.org/dist/incubator/netbeans/incubating-netbeans/incubating-10.0/incubating-netbeans-10.0-source.zip[incubating-netbeans-10.0-source.zip] in a directory of your liking.
2. `cd` to that directory, and then run `ant` to build the Apache NetBeans IDE. Once built you can run the IDE by typing `./nbbuild/netbeans/bin/netbeans`

== Community approval

As in any other Apache Project, the Apache NetBeans Community approved this release through the following voting processes in our xref:../../community/mailing-lists.adoc[mailing lists] :

- link:https://lists.apache.org/thread.html/a06ad60089470b0b52fe7e6f4c271d2fd1dcce722a5fe9b3aa008b3d@%3Cdev.netbeans.apache.org%3E[PPMC vote]
- link:https://lists.apache.org/thread.html/305d657e57d04df3d4a13c76ab732e64ef72d107fe0f769d5f4bbd80@%3Cdev.netbeans.apache.org%3E[PPMC vote result]
- link:https://lists.apache.org/thread.html/12e90e3171b85cb1b2249c59fe25caeefd9f6edf0dc14b9916b0af6f@%3Cgeneral.incubator.apache.org%3E[IPMC vote]
- link:https://lists.apache.org/thread.html/baaaee55cb4e4daf8c6d9527cfbcf15d05ef58b50f9ee6d02146afa0@%3Cgeneral.incubator.apache.org%3E[IPMC vote result]

== Release information

Please visit the link:https://cwiki.apache.org/confluence/display/NETBEANS/Apache+NetBeans+10[Apache NetBeans 10 page] for further details.


