////
     Licensed to the Apache Software Foundation (ASF) under one
     or more contributor license agreements.  See the NOTICE file
     distributed with this work for additional information
     regarding copyright ownership.  The ASF licenses this file
     to you under the Apache License, Version 2.0 (the
     "License"); you may not use this file except in compliance
     with the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing,
     software distributed under the License is distributed on an
     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
     KIND, either express or implied.  See the License for the
     specific language governing permissions and limitations
     under the License.
////
////

NOTE: 
See https://www.apache.org/dev/release-download-pages.html 
for important requirements for download pages for Apache projects.

////
= Downloading Apache NetBeans 12.2 
:jbake-type: page_noaside
:jbake-tags: download
:jbake-status: published
:keywords: Apache NetBeans 12.2 Download
:description: Apache NetBeans 12.2 Download
:toc: left
:toc-title:
:icons: font

Apache NetBeans 12.2 was released in November, 2020.
See xref:index.adoc[Apache NetBeans 12.2 Features] for a full list of features.

////
NOTE: It's mandatory to link to the source. It's optional to link to the binaries.
NOTE: It's mandatory to link against https://www.apache.org for the sums & keys. https is recommended.
NOTE: It's NOT recommended to link to github.
////
Apache NetBeans 12.2 is available for download from your closest Apache mirror.

- Binaries: 
link:https://archive.apache.org/dist/netbeans/netbeans/12.2/netbeans-12.2-bin.zip[netbeans-12.2-bin.zip] (link:https://archive.apache.org/dist/netbeans/netbeans/12.2/netbeans-12.2-bin.zip.sha512[SHA-512],
link:https://archive.apache.org/dist/netbeans/netbeans/12.2/netbeans-12.2-bin.zip.asc[PGP ASC])

- Installers:
 
* link:https://archive.apache.org/dist/netbeans/netbeans/12.2/Apache-NetBeans-12.2-bin-windows-x64.exe[Apache-NetBeans-12.2-bin-windows-x64.exe] (link:https://archive.apache.org/dist/netbeans/netbeans/12.2/Apache-NetBeans-12.2-bin-windows-x64.exe.sha512[SHA-512],
link:https://archive.apache.org/dist/netbeans/netbeans/12.2/Apache-NetBeans-12.2-bin-windows-x64.exe.asc[PGP ASC])
* link:https://archive.apache.org/dist/netbeans/netbeans/12.2/Apache-NetBeans-12.2-bin-linux-x64.sh[Apache-NetBeans-12.2-bin-linux-x64.sh] (link:https://archive.apache.org/dist/netbeans/netbeans/12.2/Apache-NetBeans-12.2-bin-linux-x64.sh.sha512[SHA-512],
link:https://archive.apache.org/dist/netbeans/netbeans/12.2/Apache-NetBeans-12.2-bin-linux-x64.sh.asc[PGP ASC])
* link:https://archive.apache.org/dist/netbeans/netbeans/12.2/Apache-NetBeans-12.2-bin-macosx.dmg[Apache-NetBeans-12.2-bin-macosx.dmg] (link:https://archive.apache.org/dist/netbeans/netbeans/12.2/Apache-NetBeans-12.2-bin-macosx.dmg.sha512[SHA-512],
link:https://archive.apache.org/dist/netbeans/netbeans/12.2/Apache-NetBeans-12.2-bin-macosx.dmg.asc[PGP ASC])

- Source: link:https://archive.apache.org/dist/netbeans/netbeans/12.2/netbeans-12.2-source.zip[netbeans-12.2-source.zip] (link:https://archive.apache.org/dist/netbeans/netbeans/12.2/netbeans-12.2-source.zip.sha512[SHA-512],
link:https://archive.apache.org/dist/netbeans/netbeans/12.2/netbeans-12.2-source.zip.asc[PGP ASC])

- Javadoc for this release is available at https://bits.netbeans.org/12.2/javadoc

////
NOTE: Using https below is highly recommended.
////
Officially, it is important that you link:https://www.apache.org/dyn/closer.cgi#verify[verify the integrity]
of the downloaded files using the PGP signatures (.asc file) or a hash (.sha512 files).
The PGP keys used to sign this release are available link:https://downloads.apache.org/netbeans/KEYS[here].

Apache NetBeans can also be installed as a self-contained link:https://snapcraft.io/netbeans[snap package] on Linux.


== Deployment Platforms

Apache NetBeans 12.2 runs on JDK LTS releases 8 and 11, as well as on JDK 15, i.e., the current JDK release at the time of this NetBeans release.

TIP: The current JDKs have an issue on Mac OS Big Sur, that causes freezes on dialogs. That could be fixed by applying the workaround described at link:https://issues.apache.org/jira/browse/NETBEANS-5037?focusedCommentId=17234878&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17234878[NETBEANS-5037] .

== Building from Source

To build Apache NetBeans 12.2 from source you need:

. A distribution of OpenJDK 8 or 11.
. Apache Ant 1.10 or greater (link:https://ant.apache.org[https://ant.apache.org]).

Once you have everything installed then:

1. Unzip link:https://archive.apache.org/dist/netbeans/netbeans/12.2/netbeans-12.2-source.zip[netbeans-12.2-source.zip]
in a directory of your liking.

[start=2]
. `cd` to that directory, and then run `ant` to build the Apache NetBeans IDE.
Once built you can run the IDE by typing `./nbbuild/netbeans/bin/netbeans`

== Community Approval

As in any other Apache Project, the Apache NetBeans Community approved this release
through the following voting processes in our xref:../../community/mailing-lists.adoc[mailing lists]:

- link:https://lists.apache.org/thread.html/rb7f838f8abb46466ff46bb00c05ecb7ac92a65f710d7f81a2c2b849b%40%3Cdev.netbeans.apache.org%3E[PMC vote]
- link:https://lists.apache.org/thread.html/r2bc401c5cc129581f31bf6dbcbde2c79cbc915d73563378f300f6dd1%40%3Cdev.netbeans.apache.org%3E[PMC vote result]

== Earlier Releases

Please visit the xref:../index.adoc[Apache NetBeans Download page]
for further details.
