////
     Licensed to the Apache Software Foundation (ASF) under one
     or more contributor license agreements.  See the NOTICE file
     distributed with this work for additional information
     regarding copyright ownership.  The ASF licenses this file
     to you under the Apache License, Version 2.0 (the
     "License"); you may not use this file except in compliance
     with the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing,
     software distributed under the License is distributed on an
     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
     KIND, either express or implied.  See the License for the
     specific language governing permissions and limitations
     under the License.
////
= Oracle Transition
:jbake-type: page
:jbake-tags: about
:jbake-status: published
:keywords: Apache NetBeans History
:description: Apache NetBeans History
:toc: left
:toc-title:
:icons: font

== Standing on our own feet

In 2016 Oracle donated the source code of NetBeans to the Apache Software Foundation (see xref:history.adoc[Our History] for details).

During the next five years Oracle has also been supporting the NetBeans Project with some server infrastructure (and a great team!). This has been of course of great help, and has allowed us to move forward. We want to thank Oracle for all this help.

In the meanwhile we have graduated from the link:https://incubator.apache.org/[Apache Incubator], have set up a regular release cycle and have started publishing maven artifacts in link:https://search.maven.org/artifact/org.apache.netbeans/netbeans-parent/2/pom[Maven Central]

As of March the 6th, 2021, we'll be standing on our own feet, and all the Apache NetBeans Project source and convenience binaries will be hosted by the link:https://www.apache.org/dev/infrastructure.html[Apache Infra Team].

This means that we won't be able to host any binaries that are not produced by the Apache Software Foundation, as stated in the link:https://infra.apache.org/release-distribution[ASF Infra Release Distribution Policy] and in the link:https://www.apache.org/legal/release-policy.html#policy[Apache Release Policy].

== Oracle's binaries and artifacts

In case you still need to access Oracle binaries or artifacts, some individuals have created a backup of those that you may want to use. Here is a list:

=== Maven repository

Jaroslav Tulach is hosting a Maven repository with all previous Oracle binaries at link:https://netbeans.apidesign.org/maven2/[https://netbeans.apidesign.org/maven2/]. You can use this repository by adding the following to your `pom.xml`:

[code, xml]
----
<build>
    <repositories>
        <repository>
            <id>netbeans</id>
            <name>NetBeans</name>
            <url>https://netbeans.apidesign.org/maven2/</url>
        </repository>
    </repositories>
<build> 
----

=== Hg mercurial repositories

- Jaroslav Tulach is hosting a clone of the Mercurial repositories at http://source.apidesign.org/hg/netbeans/
- Emilian Bold's conversion of Mercurial to git is available at https://github.com/emilianbold/netbeans-releases














