////
     Licensed to the Apache Software Foundation (ASF) under one
     or more contributor license agreements.  See the NOTICE file
     distributed with this work for additional information
     regarding copyright ownership.  The ASF licenses this file
     to you under the Apache License, Version 2.0 (the
     "License"); you may not use this file except in compliance
     with the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing,
     software distributed under the License is distributed on an
     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
     KIND, either express or implied.  See the License for the
     specific language governing permissions and limitations
     under the License.
////
= Apache NetBeans 12.1 Features
:jbake-type: page_noaside
:jbake-tags: 12.1 features
:jbake-status: published
:keywords: Apache NetBeans 12.1 IDE features
:icons: font
:description: Apache NetBeans 12.1 features
:toc: left
:toc-title: 
:toclevels: 4
:syntax: true
:source-highlighter: pygments
:experimental:
:linkattrs:

Welcome to Apache NetBeans 12.1, the first feature release of the Apache NetBeans 12 cycle!

TIP: The LTS release of the Apache NetBeans 12 cycle is Apache NetBeans 12.0. The 12.1 release has not been tested as heavily as the LTS release and may therefore be less stable. Use 12.1 to use the latest features and to provide feedback for the next LTS release, scheduled for 2021. Go here to download  xref:../nb120/nb120.adoc[Apache NetBeans 12.0], the current LTS release.

xref:nb121.adoc[Download, role="button success"]

== Highlights

The full list of pull requests integrated in the 12.1 timeframe link:https://github.com/apache/netbeans/milestone/6?closed=1[is found here], while the highlights are listed below.

=== Jakarta EE 8

- Ability to create a Jakarta EE 8 project
- Change an existing Maven web application to Jakarta EE 8.

== Java Editor

- nb-javac for Java 14 usage when running NetBeans on earlier JDK releases (link:https://github.com/apache/netbeans/pull/2277[https://github.com/apache/netbeans/pull/2277])
- New file template for creating Records (link:https://github.com/apache/netbeans/pull/2183[https://github.com/apache/netbeans/pull/2183])
- Better support for code completion for Records (link:https://github.com/apache/netbeans/pull/2222[https://github.com/apache/netbeans/pull/2222])
- Refactoring support for Records (link:https://github.com/apache/netbeans/pull/2164[https://github.com/apache/netbeans/pull/2164])

=== C/C++

Rudimentary C/C++ feature integration, which does not have as many features as the 8.2 C/C++ support, in other words, this is not fully featured, but it could help some of our users until the full support is complete. When 8.2 C/C++ plugins are installed, they should take precedence in 12.1. 

- Rudimentary C/C++ project that allows the user to provide commands for the build/run actions and some additional settings.
- Syntax highlighting using TextMate grammars.
- Code completion and other editing support is through the Language Server Protocol, using the ccls language server, which the users need to provide themselves;
-- A *very* rudimentary debugger using gdb (based on the Ant debugger, and gdb interface from CND).

More details: link:https://github.com/apache/netbeans/pull/2234[https://github.com/apache/netbeans/pull/2234]

=== Gradle

- Gradle is enabled with Java SE
- Added support for Generated Directories and proper handling of  annotation processors

=== PHP

- Add new actions for Composer (link:https://github.com/apache/netbeans/pull/2173[https://github.com/apache/netbeans/pull/2173])
- Show `false` and `true` instead of `0` and `1` as boolean values in the Variables window of the debugger (link:https://github.com/apache/netbeans/pull/2178[https://github.com/apache/netbeans/pull/2178])
- Improve/Fix code analysis features(e.g.link:https://github.com/apache/netbeans/pull/2246[https://github.com/apache/netbeans/pull/2246], link:https://github.com/apache/netbeans/pull/2249[https://github.com/apache/netbeans/pull/2249])

== HTML

- Update the validator.jar (link:https://github.com/apache/netbeans/pull/2217[https://github.com/apache/netbeans/pull/2217])
- Enable the code template completion (link:https://github.com/apache/netbeans/pull/2253[https://github.com/apache/netbeans/pull/2253])
- Code completion and syntax highlighting for <script type="module"></script> (link:https://github.com/apache/netbeans/pull/2184[https://github.com/apache/netbeans/pull/2184])

=== CSS

- Add formatting options (link:https://github.com/apache/netbeans/pull/2257[https://github.com/apache/netbeans/pull/2257]) only "Tabs And Indents"

=== Miscellaneous

- Launcher detects JDK installed by SDKMAN on Linux and Mac.
