////
     Licensed to the Apache Software Foundation (ASF) under one
     or more contributor license agreements.  See the NOTICE file
     distributed with this work for additional information
     regarding copyright ownership.  The ASF licenses this file
     to you under the Apache License, Version 2.0 (the
     "License"); you may not use this file except in compliance
     with the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing,
     software distributed under the License is distributed on an
     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
     KIND, either express or implied.  See the License for the
     specific language governing permissions and limitations
     under the License.
////
= Apache NetBeans 12.1 Features
:jbake-type: page-noaside
:jbake-tags: 12.1 features
:jbake-status: published
:keywords: Apache NetBeans 12.1 IDE features
:icons: font
:description: Apache NetBeans 12.1 features
:toc: left
:toc-title: 
:toclevels: 4
:syntax: true
:source-highlighter: pygments
:experimental:
:linkattrs:

Welcome to Apache NetBeans 12.1!

TIP: The LTS release of the Apache NetBeans 12 cycle is Apache NetBeans 12.0. The 12.1 release has not been tested as heavily as the LTS release and may therefore be less stable. Use 12.1 to use the latest features and to provide feedback for the next LTS release, scheduled for 2021. Go here to download  link:/download/nb120/nb120.html[Apache NetBeans 12.0], the current LTS release.

link:/download/nb111/nb111.html[Download, role="button success"]
