////
     Licensed to the Apache Software Foundation (ASF) under one
     or more contributor license agreements.  See the NOTICE file
     distributed with this work for additional information
     regarding copyright ownership.  The ASF licenses this file
     to you under the Apache License, Version 2.0 (the
     "License"); you may not use this file except in compliance
     with the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing,
     software distributed under the License is distributed on an
     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
     KIND, either express or implied.  See the License for the
     specific language governing permissions and limitations
     under the License.
////
= Submitting Pull Requests / Apache NetBeans
:jbake-type: page
:jbake-tags: community
:jbake-status: published
:keywords: Apache NetBeans run debug video tutorials
:description: Learn to build and debug Apache NetBeans IDE and create NetBeans Platform applications.
:toc: left
:toclevels: 4
:toc-title: 

[IMPORTANT] 
.Changes since the videos were made:
==== 
. Working with the NetBeans source now requires NB IDE 9 or later.
. The folder layout of the repository has changed to use sub-folder per cluster.
====

== Part 1: Hello Apache NetBeans Platform
video::VC8gQJknPaU[youtube]

== Part 2: Debug into the Apache NetBeans Platform
video::rufG7VE-u9s[youtube]

== Part 3: Run & Debug Apache NetBeans IDE
video::a1F2FkhZfQM[youtube]

== Part 4: Edit and Run Apache NetBeans IDE
video::iv4osiFZDP0[youtube]

== Part 5: Debug the Sources of Apache NetBeans IDE
video::UaGdctQWt_4[youtube]
