////
     Licensed to the Apache Software Foundation (ASF) under one
     or more contributor license agreements.  See the NOTICE file
     distributed with this work for additional information
     regarding copyright ownership.  The ASF licenses this file
     to you under the Apache License, Version 2.0 (the
     "License"); you may not use this file except in compliance
     with the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing,
     software distributed under the License is distributed on an
     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
     KIND, either express or implied.  See the License for the
     specific language governing permissions and limitations
     under the License.
////
= Participate / Apache NetBeans
:jbake-type: page
:jbake-tags: community
:jbake-status: published
:keywords: Participate in Apache NetBeans 
:description: Participate in Apache NetBeans 
:toc: left
:toclevels: 4
:toc-title: 

The Apache Software Foundation has set up link:http://community.apache.org/[a
specific website] designed to help newcomers take their first steps towards
being part of our Community. 

You can participate in the Apache NetBeans (Incubating) Project in many different ways.
Here are some ideas:

== link:submit-pr.html[Contributing code]
See link:submit-pr.html[contributing code] to learn how to contribute code to the Apache NetBeans project.

== link:report-issue.html[Reporting issues]
See link:report-issue.html[reporting issues] for instructions on how to report an issue.

== link:netcat.html[Join the NetCAT program]
The NetBeans Community Acceptance Test (link:netcat.html[NetCAT]) has helped stabilize development
builds for years.

[[documentation]]
== Improving the documentation
We will be porting existing NetBeans documentation soon. Keep posted for information on how to help with this task.


