= Participate / Apache NetBeans
:jbake-type: page
:jbake-tags: community
:jbake-status: published
:keywords: Participate in Apache NetBeans 
:description: Participate in Apache NetBeans 
:toc: left
:toclevels: 4
:toc-title: 

The Apache Software Foundation has set up link:http://community.apache.org/[a
specific website] designed to help newcomers take their first steps towards
being part of our Community. 

You can participate in the Apache NetBeans (Incubating) Project in many different ways.
Here are some ideas:

== link:submit-pr.html[Contributing code]
See link:submit-pr.html[contributing code] to learn how to contribute code to the Apache NetBeans project.

== link:report-issue.html[Reporting issues]
See link:report-issue.html[reporting issues] for instructions on how to report an issue.

== Join the link:netcat.html[NetCAT] program
The NetBeans Community Acceptance Test (link:netcat.html[NetCAT]) has helped stabilize development
builds for years.

[[documentation]]
== Improving the documentation
We will be porting existing NetBeans documentation soon. Keep posted for information on how to help with this task.


