////
     Licensed to the Apache Software Foundation (ASF) under one
     or more contributor license agreements.  See the NOTICE file
     distributed with this work for additional information
     regarding copyright ownership.  The ASF licenses this file
     to you under the Apache License, Version 2.0 (the
     "License"); you may not use this file except in compliance
     with the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing,
     software distributed under the License is distributed on an
     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
     KIND, either express or implied.  See the License for the
     specific language governing permissions and limitations
     under the License.
////
= Reporting issues
:jbake-type: page
:jbake-tags: community
:jbake-status: published
:keywords: Apache NetBeans JIRA issue report
:description: Apache NetBeans Reporting Issues
:toc: left
:toc-title:

If you have found a bug in the application, please help Apache NetBeans by reporting this problem to our bug tracking system. Click View Data button, copy the exception and submit it together with detailed information about what you were trying to achieve before the problem occurred in link:https://issues.apache.org/jira/projects/NETBEANS/issues[JIRA]. 

Thank you for helping us make Apache NetBeans better!

== Note

Please provide the following information to reproduce your issues when you submit them.

- Example code (Attachments or Description)
- Example project (Attachments)
- Screenshots (Attachments)
- Exact steps e.g. 1. Create an empty project, 2. Write the following code, 3. Something... (Description)
- Actual results (Description)
- Expected results (Description)
- NetBeans version (Affects Version/s)
- JDK version (Environment)
- OS (Environment)
