////
     Licensed to the Apache Software Foundation (ASF) under one
     or more contributor license agreements.  See the NOTICE file
     distributed with this work for additional information
     regarding copyright ownership.  The ASF licenses this file
     to you under the Apache License, Version 2.0 (the
     "License"); you may not use this file except in compliance
     with the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing,
     software distributed under the License is distributed on an
     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
     KIND, either express or implied.  See the License for the
     specific language governing permissions and limitations
     under the License.
////
= Reporting issues / Apache NetBeans
:jbake-type: page
:jbake-tags: community
:jbake-status: published
:keywords: Apache NetBeans JIRA issue report
:description: Apache NetBeans Reporting Issues
:toc: left
:toc-title:

== Reporting Issues

If you have found a bug in the application, please help Apache NetBeans by reporting this problem to our bug tracking system. Click View Data button, copy the exception and submit it together with detailed information about what you were trying to achieve before the problem occurred in JIRA. Thank you for helping us make Apache NetBeans better!

We use the link:https://issues.apache.org/jira/projects/NETBEANS/summary[JIRA] issue tracker to track issues.

To report an issue please:

. Search JIRA to see if the issue has been already reported by any other user.
. If not then please link:https://issues.apache.org/jira/secure/CreateIssue!default.jspa[Create an issue] specifying the affected component.
