////
     Licensed to the Apache Software Foundation (ASF) under one
     or more contributor license agreements.  See the NOTICE file
     distributed with this work for additional information
     regarding copyright ownership.  The ASF licenses this file
     to you under the Apache License, Version 2.0 (the
     "License"); you may not use this file except in compliance
     with the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing,
     software distributed under the License is distributed on an
     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
     KIND, either express or implied.  See the License for the
     specific language governing permissions and limitations
     under the License.
////
= Reporting issues
:jbake-type: page
:jbake-tags: community
:jbake-status: published
:keywords: Apache NetBeans issue report
:description: Apache NetBeans Reporting Issues

If you have found a bug in the application, please help Apache NetBeans by reporting this problem
to link:https://github.com/apache/netbeans/issues[our issue tracking on GitHub].

Thank you for helping us make Apache NetBeans better!

== Note

Please make sure the issue can be replicated with the latest Apache NetBeans release,
and has not already been reported. Provide enough information for someone to be able
to reproduce the problem. Sufficient information might include -

- Example code (Attachments or Description)
- Example project (Attachments)
- Screenshots (Attachments)
- Exact steps e.g. 1. Create an empty project, 2. Write the following code, 3. Something... (Description)
- Actual results (Description)
- Expected results (Description)
- JDK version (Environment)
- OS (Environment)

link:https://github.com/apache/netbeans/issues[Report issue, role="button success"]

