// 
//     Licensed to the Apache Software Foundation (ASF) under one
//     or more contributor license agreements.  See the NOTICE file
//     distributed with this work for additional information
//     regarding copyright ownership.  The ASF licenses this file
//     to you under the Apache License, Version 2.0 (the
//     "License"); you may not use this file except in compliance
//     with the License.  You may obtain a copy of the License at
// 
//       http://www.apache.org/licenses/LICENSE-2.0
// 
//     Unless required by applicable law or agreed to in writing,
//     software distributed under the License is distributed on an
//     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
//     KIND, either express or implied.  See the License for the
//     specific language governing permissions and limitations
//     under the License.
//

= Autoload
:jbake-type: wiki
:jbake-tags: wiki, devfaq, needsreview
:jbake-status: published
:keywords: Apache NetBeans wiki Autoload
:description: Apache NetBeans wiki Autoload
:toc: left
:toc-title:
:syntax: true

The link:autoload.asciidoc[autoload] in the link:NetBeans.asciidoc[NetBeans] module system world means that certain module is turned on when _needed_. In contrast to regular modules which require some manual action (user locating a module and activating it) to turn them on, the link:autoload.asciidoc[autoload] modules are opaque for users and managed solely by the infrastructure. As soon as there is some module needing (by dependency or require/needs token) an link:autoload.asciidoc[autoload] module, the infrastructure enables it.

In the link:Netigso.asciidoc[OSGi] mode, the meaning of link:autoload.asciidoc[autoload] remains as close as the original meaning. The bundle JAR is registered to the underlaying link:OSGi.asciidoc[OSGi] framework, but it is not _started_ until there is some NetBeans module which would depend on the bundle. If there is no such link:NetBeans.asciidoc[NetBeans] module, the link:OSGi.asciidoc[OSGi] bundle remains in _installed_ state (or _resolved_?).

The link:autoload.asciidoc[autoload] mode is most suitable for link:OSGi.asciidoc[OSGi] bundles which shall be left in the full control of the link:OSGi.asciidoc[OSGi] container. For example there can be other link:OSGi.asciidoc[OSGi] bundles which may later _start_ such bundles. Such enablement is outside of control of the link:NetBeans.asciidoc[NetBeans] module system and is temporary (on subsequent launch of the system the module remains link:autoload.asciidoc[autoload]).

=== Apache Migration Information

The content in this page was kindly donated by Oracle Corp. to the
Apache Software Foundation.

This page was exported from link:http://wiki.netbeans.org/Autoload[http://wiki.netbeans.org/Autoload] , 
that was last modified by NetBeans user Jtulach 
on 2010-07-16T09:32:24Z.


*NOTE:* This document was automatically converted to the AsciiDoc format on 2018-02-07, and needs to be reviewed.
