// 
//     Licensed to the Apache Software Foundation (ASF) under one
//     or more contributor license agreements.  See the NOTICE file
//     distributed with this work for additional information
//     regarding copyright ownership.  The ASF licenses this file
//     to you under the Apache License, Version 2.0 (the
//     "License"); you may not use this file except in compliance
//     with the License.  You may obtain a copy of the License at
// 
//       http://www.apache.org/licenses/LICENSE-2.0
// 
//     Unless required by applicable law or agreed to in writing,
//     software distributed under the License is distributed on an
//     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
//     KIND, either express or implied.  See the License for the
//     specific language governing permissions and limitations
//     under the License.
//

= DevFaqLic3rdPartyComponents
:jbake-type: wiki
:jbake-tags: wiki, devfaq, needsreview
:jbake-status: published
:keywords: Apache NetBeans wiki DevFaqLic3rdPartyComponents
:description: Apache NetBeans wiki DevFaqLic3rdPartyComponents
:toc: left
:toc-title:
:syntax: true

== What third party libraries are in the Platform and what are their licenses?

You can find the information about NetBeans code license at link:http://netbeans.org/about/legal/index.html[http://netbeans.org/about/legal/index.html].

Matrix of third-party libraries can be found in Third Party License link for the particular version at link:http://netbeans.org/about/legal/product-licences.html[http://netbeans.org/about/legal/product-licences.html].

Note that if your application depends not only on Platform (modules from 'platform' cluster) but also on other parts of the NetBeans IDE (e.g. modules from the 'ide', or 'java' clusters) there may be derived dependencies on other 3rd party libraries.

=== Apache Migration Information

The content in this page was kindly donated by Oracle Corp. to the
Apache Software Foundation.

This page was exported from link:http://wiki.netbeans.org/DevFaqLic3rdPartyComponents[http://wiki.netbeans.org/DevFaqLic3rdPartyComponents] , 
that was last modified by NetBeans user Anebuzelsky 
on 2011-12-27T17:04:56Z.


*NOTE:* This document was automatically converted to the AsciiDoc format on 2018-02-07, and needs to be reviewed.
