// 
//     Licensed to the Apache Software Foundation (ASF) under one
//     or more contributor license agreements.  See the NOTICE file
//     distributed with this work for additional information
//     regarding copyright ownership.  The ASF licenses this file
//     to you under the Apache License, Version 2.0 (the
//     "License"); you may not use this file except in compliance
//     with the License.  You may obtain a copy of the License at
// 
//       http://www.apache.org/licenses/LICENSE-2.0
// 
//     Unless required by applicable law or agreed to in writing,
//     software distributed under the License is distributed on an
//     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
//     KIND, either express or implied.  See the License for the
//     specific language governing permissions and limitations
//     under the License.
//

= DevFaqVersionNumber
:jbake-type: wiki
:jbake-tags: wiki, devfaq, needsreview
:jbake-status: published
:keywords: Apache NetBeans wiki DevFaqVersionNumber
:description: Apache NetBeans wiki DevFaqVersionNumber
:toc: left
:toc-title:
:syntax: true

=== How do I set the version number?

There are two ways to set the version number shown in the Help... About dialog.

* The easy way is to set the system property `netbeans.buildnumber` to some value in your application.  
* The harder way is to put this key/value `currentVersion=My Product 1.2.3` into the file named `"branding/modules/org-netbeans-core.jar/org/netbeans/core/ui/Bundle.properties"` below your suite, then rebuild and run.
* In NB 6.5 and later is the file location different: `"branding/core/core.jar/org/netbeans/core/startup/Bundle.properties"`

=== How do I set the version number automatically in maven-based applications?

Within your branding-module use Maven placeholders in Bundle.properties and  within the pom.xml filter the bundle by the maven-resources-plugin.

*Note:* Some of the files below are ignored by default in version control by Netbeans so you might need to add them to preserve the changes.

src/main/nbm-branding/core/core.jar/org/netbeans/core/startup/Bundle.properties:

[source,java]
----

currentVersion=My app ${project.version}
LBL_splash_window_title=Starting My app ${project.version}
----

src/main/nbm-branding/modules/org-netbeans-core-windows.jar/org/netbeans/core/windows/view/ui/Bundle.properties:

[source,java]
----

CTL_MainWindow_Title=My app ${project.version}
CTL_MainWindow_Title_No_Project=My app ${project.version}
----

src/main/nbm-branding/modules/org-netbeans-core.jar/org/netbeans/core/ui/Bundle.properties:

[source,java]
----

LBL_ProductInformation=My app ${project.version}
----

pom.xml:

[source,xml]
----

    <build>
        <resources>
            <resource>
                <directory>${basedir}/src/main/nbm-branding</directory>
                <!-- f.e. allow replacing ${project.version} in all property files below src/main/nbm-branding -->
                <includes>
                    <include>**/*.properties</include>
                </includes>
                <filtering>true</filtering>
                <targetPath>${basedir}/target/filtered-nbm-branding</targetPath>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>nbm-maven-plugin</artifactId>
                <configuration>
                    <!-- use previously filtered branding sources -->
                    <brandingSources>${basedir}/target/filtered-nbm-branding</brandingSources>
                </configuration>
            </plugin>
            <!-- ... -->
        </plugins>
    </build>
----

=== Apache Migration Information

The content in this page was kindly donated by Oracle Corp. to the
Apache Software Foundation.

This page was exported from link:http://wiki.netbeans.org/DevFaqVersionNumber[http://wiki.netbeans.org/DevFaqVersionNumber] , 
that was last modified by NetBeans user Javydreamercsw 
on 2017-02-01T14:34:50Z.


*NOTE:* This document was automatically converted to the AsciiDoc format on 2018-02-07, and needs to be reviewed.
