// 
//     Licensed to the Apache Software Foundation (ASF) under one
//     or more contributor license agreements.  See the NOTICE file
//     distributed with this work for additional information
//     regarding copyright ownership.  The ASF licenses this file
//     to you under the Apache License, Version 2.0 (the
//     "License"); you may not use this file except in compliance
//     with the License.  You may obtain a copy of the License at
// 
//       http://www.apache.org/licenses/LICENSE-2.0
// 
//     Unless required by applicable law or agreed to in writing,
//     software distributed under the License is distributed on an
//     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
//     KIND, either express or implied.  See the License for the
//     specific language governing permissions and limitations
//     under the License.
//

= DevFaqFileEditorContextMenuAddition
:jbake-type: wiki
:jbake-tags: wiki, devfaq, needsreview
:jbake-status: published
:keywords: Apache NetBeans wiki DevFaqFileEditorContextMenuAddition
:description: Apache NetBeans wiki DevFaqFileEditorContextMenuAddition
:toc: left
:toc-title:
:syntax: true

=== Can I add a menu item to the context menu of the Java source editor?

Yes. In NetBeans 5.0 and later there is a wizard available for NetBeans modules which does this for you. Just run *New File | NetBeans Module Development | Action*, as an action type choose *Conditionally Enabled*. On the next step choose `text/x-java` in the *Editor Context Menu Item* combobox, finish the wizard and you are done. For more information you may press the *Help* button available at the bottom of each step of the wizard.

In NetBeans 4.1 you just need to insert an action (e.g. `*.instance` ) into the folder `Editors/text/x-java/Popup/` in your module's XML layer.

---

Applies to: all versions of NetBeans

Related: link:DevFaqFileContextMenuAddition.asciidoc[DevFaqFileContextMenuAddition]

=== Apache Migration Information

The content in this page was kindly donated by Oracle Corp. to the
Apache Software Foundation.

This page was exported from link:http://wiki.netbeans.org/DevFaqFileEditorContextMenuAddition[http://wiki.netbeans.org/DevFaqFileEditorContextMenuAddition] , 
that was last modified by NetBeans user Vstejskal 
on 2010-06-16T13:36:58Z.


*NOTE:* This document was automatically converted to the AsciiDoc format on 2018-02-07, and needs to be reviewed.
