// 
//     Licensed to the Apache Software Foundation (ASF) under one
//     or more contributor license agreements.  See the NOTICE file
//     distributed with this work for additional information
//     regarding copyright ownership.  The ASF licenses this file
//     to you under the Apache License, Version 2.0 (the
//     "License"); you may not use this file except in compliance
//     with the License.  You may obtain a copy of the License at
// 
//       http://www.apache.org/licenses/LICENSE-2.0
// 
//     Unless required by applicable law or agreed to in writing,
//     software distributed under the License is distributed on an
//     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
//     KIND, either express or implied.  See the License for the
//     specific language governing permissions and limitations
//     under the License.
//

= DevFaqChangeLookAndFeel
:jbake-type: wiki
:jbake-tags: wiki, devfaq, needsreview
:jbake-status: published
:keywords: Apache NetBeans wiki DevFaqChangeLookAndFeel
:description: Apache NetBeans wiki DevFaqChangeLookAndFeel
:toc: left
:toc-title:
:syntax: true

=== How can I set the Swing look and feel on startup?

Generally, you can change the look and feel either by passing command line arguments, e.g.<pre>
netbeans --laf javax.swing.plaf.metal.MetalLookAndFeel
</pre>
or do so programmatically on startup in a module's `link:DevFaqModulesGeneral.asciidoc[ModuleInstall]` class (generally if you're installing a custom look and feel, you probably want to have a separate module to do that; link:http://substance-netbeans.dev.java.net[some look and feels] provide NetBeans modules to make it easy to use them.

If you want to test running with a different look and feel during development of your application, and you know it will be on the application's classpath, see the example in link:DevFaqPassCommandLineArgumentsAtDevTime.asciidoc[DevFaqPassCommandLineArgumentsAtDevTime] for how to include `--laf` in the runtime arguments to your module suite.

=== Apache Migration Information

The content in this page was kindly donated by Oracle Corp. to the
Apache Software Foundation.

This page was exported from link:http://wiki.netbeans.org/DevFaqChangeLookAndFeel[http://wiki.netbeans.org/DevFaqChangeLookAndFeel] , 
that was last modified by NetBeans user Skygo 
on 2013-12-16T19:56:35Z.


*NOTE:* This document was automatically converted to the AsciiDoc format on 2018-02-07, and needs to be reviewed.
