// 
//     Licensed to the Apache Software Foundation (ASF) under one
//     or more contributor license agreements.  See the NOTICE file
//     distributed with this work for additional information
//     regarding copyright ownership.  The ASF licenses this file
//     to you under the Apache License, Version 2.0 (the
//     "License"); you may not use this file except in compliance
//     with the License.  You may obtain a copy of the License at
// 
//       http://www.apache.org/licenses/LICENSE-2.0
// 
//     Unless required by applicable law or agreed to in writing,
//     software distributed under the License is distributed on an
//     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
//     KIND, either express or implied.  See the License for the
//     specific language governing permissions and limitations
//     under the License.
//

= DevFaqPropertySheetHideDescription
:jbake-type: wiki
:jbake-tags: wiki, devfaq, needsreview
:jbake-status: published
:keywords: Apache NetBeans wiki DevFaqPropertySheetHideDescription
:description: Apache NetBeans wiki DevFaqPropertySheetHideDescription
:toc: left
:toc-title:
:syntax: true

== How do I hide the description area in property window

By tweaking the preferences of the "showDescriptionArea". In any layer.xml file (for example the one of branding) add

[source,java]
----

    &amp;lt;folder name="Preferences"&amp;gt;
        &amp;lt;folder name="org"&amp;gt;
            &amp;lt;folder name="openide"&amp;gt;
                &amp;lt;file name="explorer.properties" url="explorer.properties"/&amp;gt;
            &amp;lt;/folder&amp;gt;
        &amp;lt;/folder&amp;gt;
    &amp;lt;/folder&amp;gt;
----

and then next to your layer.xml file create the explorer.properties that contains:

[source,java]
----

showDescriptionArea=false
sortOrder=0
----

I found this by looking at the PropUtils class in the NBP sources.

Taken from mailing list, contributed by Jean-Marc Borer

=== Apache Migration Information

The content in this page was kindly donated by Oracle Corp. to the
Apache Software Foundation.

This page was exported from link:http://wiki.netbeans.org/DevFaqPropertySheetHideDescription[http://wiki.netbeans.org/DevFaqPropertySheetHideDescription] , 
that was last modified by NetBeans user Markiewb 
on 2016-04-10T10:27:05Z.


*NOTE:* This document was automatically converted to the AsciiDoc format on 2018-02-07, and needs to be reviewed.
