// 
//     Licensed to the Apache Software Foundation (ASF) under one
//     or more contributor license agreements.  See the NOTICE file
//     distributed with this work for additional information
//     regarding copyright ownership.  The ASF licenses this file
//     to you under the Apache License, Version 2.0 (the
//     "License"); you may not use this file except in compliance
//     with the License.  You may obtain a copy of the License at
// 
//       http://www.apache.org/licenses/LICENSE-2.0
// 
//     Unless required by applicable law or agreed to in writing,
//     software distributed under the License is distributed on an
//     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
//     KIND, either express or implied.  See the License for the
//     specific language governing permissions and limitations
//     under the License.
//

= DevFaqPlatformRuntimeProperties
:jbake-type: wiki
:jbake-tags: wiki, devfaq, needsreview
:jbake-status: published
:keywords: Apache NetBeans wiki DevFaqPlatformRuntimeProperties
:description: Apache NetBeans wiki DevFaqPlatformRuntimeProperties
:toc: left
:toc-title:
:syntax: true

== I want to set some flags or CLI arguments for running my NB RCP/Platform based application (such as disable assertions).  How do I do that?

To disable assertions or set some other VM property for your application, there are two places to pay attention to.  First, `$APP_HOME/etc/*.conf` in your distribution should set things for users of your application - do this for things that should be set for any user.

You also will probably want to test these settings - and `*.conf` is not going to be used when you launch your application by running your project from Ant (nor the NetBeans IDE).  So to handle this, you can set any of the properties documented in `$NB_HOME/harness/README`.  For example, to disable assertions when testing your application from the IDE, edit your module suite's `nbproject/project.properties` to include `run.args.extra=-J-da` or similar.

See `$NB_HOME/harness/README` in your copy of NetBeans for the full list of properties that affect how NetBeans-based-applications are run when developing them in the IDE.

<hr/>
Applies to: NetBeans 6.5 and above

=== Apache Migration Information

The content in this page was kindly donated by Oracle Corp. to the
Apache Software Foundation.

This page was exported from link:http://wiki.netbeans.org/DevFaqPlatformRuntimeProperties[http://wiki.netbeans.org/DevFaqPlatformRuntimeProperties] , 
that was last modified by NetBeans user Rmichalsky 
on 2009-12-02T15:24:03Z.


*NOTE:* This document was automatically converted to the AsciiDoc format on 2018-02-07, and needs to be reviewed.
