// 
//     Licensed to the Apache Software Foundation (ASF) under one
//     or more contributor license agreements.  See the NOTICE file
//     distributed with this work for additional information
//     regarding copyright ownership.  The ASF licenses this file
//     to you under the Apache License, Version 2.0 (the
//     "License"); you may not use this file except in compliance
//     with the License.  You may obtain a copy of the License at
// 
//       http://www.apache.org/licenses/LICENSE-2.0
// 
//     Unless required by applicable law or agreed to in writing,
//     software distributed under the License is distributed on an
//     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
//     KIND, either express or implied.  See the License for the
//     specific language governing permissions and limitations
//     under the License.
//

= Настройка сервера баз данных MySQL в операционной системе Windows
:jbake-type: tutorial
:jbake-tags: tutorials 
:jbake-status: published
:icons: font
:syntax: true
:source-highlighter: pygments
:toc: left
:toc-title:
:description: Настройка сервера баз данных MySQL в операционной системе Windows - Apache NetBeans
:keywords: Apache NetBeans, Tutorials, Настройка сервера баз данных MySQL в операционной системе Windows

Сервер баз данных MySQL является одним из наиболее популярных среди серверов баз данных с открытым исходным кодом, используемых при разработке веб-приложений.

Этот документ рекомендует использовать последовательность действий по настройке сервера базы данных MySQL версии 5.6 в ОС Windows. Сведения о конфигурации MySQL не рассматриваются, приводитсятолько последовательность необходимых шагов.

Подробнее об установке и настройке сервера баз данных MySQL для других операционных систем см. в документации link:http://dev.mysql.com/doc/refman/5.6/en/installing.html[+Установка и обновление MySQL+].

*Примечание.* link:../../72/ide/install-and-configure-mysql-server.html[+ Настройка сервера баз данных MySQL версии 5.1 в операционной системе Windows+] - этот документ содержит инструкции по установке сервера MySQL версии 5.1 в Windows.





== Начало загрузки

1. Перейдите по адресу link:http://dev.mysql.com/downloads/installer/[+http://dev.mysql.com/downloads/installer/+].
2. Нажмите кнопку 'Загрузить'.
3. Сохраните файл программы установки на вашем компьютере.

<<top,В начало>>


== Начало установки

После завершения загрузки запустите программу установки следующим образом.

1. Щелкните правой кнопкой мыши загруженный установочный файл (например,  ``mysql-installer-community-5.6.14.0.msi`` ) и выберите пункт 'Выполнить'.
Запустится программа установки MySQL.

[start=2]
. На панели приветствия выберите 'Установить продукты MySQL'.

[start=3]
. На панели информации о лицензии ознакомьтесь с лицензионным соглашением, установите флажок принятия и нажмите кнопку 'Далее'.

[start=4]
. На панели 'Найти последние продукты' нажмите кнопку 'Выполнить'. 
После завершения операции нажмите кнопку 'Далее'.

[start=5]
. На панели "Тип настройки" выберите параметр "Пользовательская", а затем нажмите кнопку "Далее".

[start=6]
. На панели 'Выбор компонентов обеспечения' убедитесь, что выбран MySQL Server 5.6.x, и нажмите кнопку 'Далее'.

[start=7]
. На панели 'Проверить требования' нажмите кнопку 'Далее'.

[start=8]
. На панели 'Установка' нажмите кнопку 'Выполнить'.
После успешного завершения установки сервера на панели 'Установка' отображается информационное сообщение. Нажмите кнопку "Далее".

[start=9]
. На странице 'Настройка' нажмите кнопку 'Далее'.

[start=10]
. На первой странице конфигурации сервера MySQL (1/3) установите следующие параметры:
* *Тип конфигурации сервера*. Выберите вариант 'Компьютер для разработки'.
* *Включите поддержку сети TCP/IP*. Убедитесь, что флажок установлен, и задайте следующие параметры ниже:
* *Номер порта*. Укажите порт подключения. По умолчанию установлено значение 3306; не следует изменять его без необходимости.
* *Откройте порт брандмауэра для доступа к сети*. Выберите исключение добавления брандмауэра для указанного порта.
* *Расширенная настройка.* Выберите флажок 'Показать расширенные параметры' для отображения дополнительной страницы конфигурации для настройки расширенных параметров для экземпляра сервера (если требуется).

*Примечание.* При выборе этого параметра необходимо перейти к панели для установки параметров сети, где будет отключен брандмауэр для порта, используемого сервером MySQL.

Нажмите кнопку "Далее".

[start=11]
. На второй странице конфигурации сервера MySQL (2/3) установите следующие параметры:
* *Пароль учетной записи root*.
* *Пароль root для MySQL*. Введите пароль пользователя root.
* *Повторите ввод пароля*. Повторно введите пароль пользователя root.

*Примечание.* Пользователь root - это пользователь, который имеет полный доступ к серверу баз данных MySQL - создание, обновление и удаление пользователей и так далее. Запомните пароль пользователя root (администратора) – он понадобится вам при создании примера базы данных.

* *Учетные записи пользователя MySQL*. Нажмите кнопку 'Добавить пользователя' для создания учетной записи пользователя. В диалоговом окне 'Сведения о пользователе MySQL' введите имя пользователя, роль базы данных и пароль (например,  ``!phpuser`` ). Нажмите кнопку "ОК".
Нажмите кнопку "Далее".

. На третьей странице конфигурации сервера MySQL (3/3) установите следующие параметры:
* *Имя службы Windows*. Укажите имя службы Windows, которая будет использоваться для экземпляра сервера MySQL.
* *Запустите сервер MySQL при запуске системы*. Не снимайте этот флажок, если сервер MySQL требуется для автоматического запуска при запуске системы.
* *Запуск службы Windows в качестве*. Возможны следующие варианты.
* *Стандартная системная учетная запись*. Рекомендуется для большинства сценариев.
* *Нестандартный пользователь*. Существующая учетная запись пользователя рекомендуется для сложных сценариев.
Нажмите кнопку "Далее".

. На странице 'Обзор конфигурации' нажмите кнопку 'Далее'.
. После успешного завершения настройки на панели 'Завершение' появляется информационное сообщение. Нажмите кнопку "Завершить".

*Примечание.* Для проверки успешности настройки запустите диспетчер задач. Если  ``MySQLd-nt.exe``  присутствует в списке 'Процессы', сервер базы данных запущен.

<<top,В начало>>

link:/about/contact_form.html?to=3&subject=Feedback:%20Setting%20Up%20the%20MySQL%20Database%20Server%20in%20the%20Windows%20Operating%20System[+Отправить отзыв по этому учебному курсу+]



== Дополнительные сведения

* link:http://www.oracle.com/pls/topic/lookup?ctx=nb8000&id=NBDAG1790[+Работа с базами данных и подключение к ним+] в документе _Разработка приложений в IDE NetBeans_
* link:../../trails/php.html[+Учебная карта по PHP+]
* link:mysql.html[+Подключение к базе данных MySQL+]
* link:http://www.mysql.com/why-mysql/java/[+MySQL и Java: материалы+]
* link:http://dev.mysql.com/doc/refman/5.6/en/index.html[+Справочное руководство по MySQL 5.6+]

<<top,В начало>>

