
////
     Licensed to the Apache Software Foundation (ASF) under one
     or more contributor license agreements.  See the NOTICE file
     distributed with this work for additional information
     regarding copyright ownership.  The ASF licenses this file
     to you under the Apache License, Version 2.0 (the
     "License"); you may not use this file except in compliance
     with the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing,
     software distributed under the License is distributed on an
     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
     KIND, either express or implied.  See the License for the
     specific language governing permissions and limitations
     under the License.
////
= Apache NetBeans 11.1 Features
:jbake-type: page
:jbake-tags: 11.1 features
:jbake-status: published
:keywords: Apache NetBeans 11.1 IDE features
:icons: font
:description: Apache NetBeans 11.1 features
:toc: left
:toc-title: 
:toclevels: 4
:syntax: true
:source-highlighter: pygments
:experimental:

Apache NetBeans 11.1 is the first Apache NetBeans release outside the Apache Incubator and the link:https://cwiki.apache.org/confluence/display/NETBEANS/Release+Schedule[first release of the new quarterly release].

== Java EE

[.feature]
--
Payara integration out of the box, with thanks to the Payara team. Java EE 8 support for Maven-based and Gradle-based Web applications.

--

== Java

[.feature]
--
As a result you can now:

- Integration of support for JEP-330.

--

== Kotlin

[.feature]
--
As a result you can now:

- Syntax coloring for .kt files.

-- 

== Web Frontend: JavaScript/HTML5/PHP

[.feature]
--
As a result you can now:

- PHP 7.4.

-- 

== NetBeans Platform / NetBeans APIs

[.feature]
--
As a result you can now:

- Create Mode from client code.

-- 

== Appearance

[.feature]
--
As a result you can now:

- HiDPI splash screen with product version.

-- 

== Miscellaneous

[.feature]
--
As a result you can now:

- Popupswitcher npe fixes.

-- 

