////
     Licensed to the Apache Software Foundation (ASF) under one
     or more contributor license agreements.  See the NOTICE file
     distributed with this work for additional information
     regarding copyright ownership.  The ASF licenses this file
     to you under the Apache License, Version 2.0 (the
     "License"); you may not use this file except in compliance
     with the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing,
     software distributed under the License is distributed on an
     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
     KIND, either express or implied.  See the License for the
     specific language governing permissions and limitations
     under the License.
////
= Preferences API and NetBeans IDE (Part 2) 
:jbake-type: page
:jbake-tags: community
:jbake-status: published
:keywords: blog entry preferences_api_and_netbeans_ide1
:description: blog entry preferences_api_and_netbeans_ide1
:toc: left
:toclevels: 4
:toc-title: 


The blog entry is archived at link:https://web.archive.org/web/20131216123710/https://blogs.oracle.com/geertjan/entry/preferences_api_and_netbeans_ide1[Web archive]

