////
     Licensed to the Apache Software Foundation (ASF) under one
     or more contributor license agreements.  See the NOTICE file
     distributed with this work for additional information
     regarding copyright ownership.  The ASF licenses this file
     to you under the Apache License, Version 2.0 (the
     "License"); you may not use this file except in compliance
     with the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing,
     software distributed under the License is distributed on an
     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
     KIND, either express or implied.  See the License for the
     specific language governing permissions and limitations
     under the License.
////
////

NOTE: 
See https://www.apache.org/dev/release-download-pages.html 
for important requirements for download pages for Apache projects.

////
= Downloading Apache NetBeans 16
:jbake-type: page_noaside
:jbake-tags: download
:jbake-status: published
:keywords: Apache NetBeans 16 Download
:description: Apache NetBeans 16 Download
:toc: left
:toc-title:
:icons: font

// check version above
:netbeans-version: 16

// base URLs - when archiving, delete the next 2 lines and uncomment the following 2
:url-download: https://www.apache.org/dyn/closer.cgi/netbeans/
:url-download-keychecksum: https://downloads.apache.org/netbeans/
// :url-download: https://archive.apache.org/dist/netbeans/
// :url-download-keychecksum: https://archive.apache.org/dist/netbeans/

//// 
url-download depends of release status archived or not
https://archive.apache.org/dist/netbeans/  (//archived)
https://www.apache.org/dyn/closer.cgi/netbeans/ (//current)

url-download-keychecksum depends of release status archived or not
https://archive.apache.org/dist/netbeans/  (//archived)
https://downloads.apache.org/netbeans/ (//current)
////

Apache NetBeans {netbeans-version} was released on November 30, 2022. See link:https://github.com/apache/netbeans/releases/tag/{netbeans-version}[Release Notes on GitHub] for all changes in Apache NetBeans {netbeans-version}.

////
NOTE: It's mandatory to link to the source. It's optional to link to the binaries.
NOTE: It's mandatory to link against https://www.apache.org for the sums & keys. https is recommended.
NOTE: It's NOT recommended to link to github.
////
Apache NetBeans {netbeans-version} is available for download from your closest Apache mirror.

- Binaries: 
link:{url-download}netbeans/{netbeans-version}/netbeans-{netbeans-version}-bin.zip[netbeans-{netbeans-version}-bin.zip] (link:{url-download-keychecksum}netbeans/{netbeans-version}/netbeans-{netbeans-version}-bin.zip.sha512[SHA-512],
link:{url-download-keychecksum}netbeans/{netbeans-version}/netbeans-{netbeans-version}-bin.zip.asc[PGP ASC])

- Installers:

* link:{url-download}netbeans-installers/{netbeans-version}/Apache-NetBeans-{netbeans-version}-bin-windows-x64.exe[Apache-NetBeans-{netbeans-version}-bin-windows-x64.exe] (link:{url-download-keychecksum}netbeans-installers/{netbeans-version}/Apache-NetBeans-{netbeans-version}-bin-windows-x64.exe.sha512[SHA-512],
link:{url-download-keychecksum}netbeans-installers/{netbeans-version}/Apache-NetBeans-{netbeans-version}-bin-windows-x64.exe.asc[PGP ASC])
* link:{url-download}netbeans-installers/{netbeans-version}/Apache-NetBeans-{netbeans-version}-bin-macosx.dmg[Apache-NetBeans-{netbeans-version}-bin-macosx.dmg] (link:{url-download-keychecksum}netbeans-installers/{netbeans-version}/Apache-NetBeans-{netbeans-version}-bin-macosx.dmg.sha512[SHA-512],
link:{url-download-keychecksum}netbeans-installers/{netbeans-version}/Apache-NetBeans-{netbeans-version}-bin-macosx.dmg.asc[PGP ASC])
* link:{url-download}netbeans-installers/{netbeans-version}/apache-netbeans_{netbeans-version}-1_all.deb[apache-netbeans_{netbeans-version}-1_all.deb] (link:{url-download-keychecksum}netbeans-installers/{netbeans-version}/apache-netbeans_{netbeans-version}-1_all.deb.sha512[SHA-512],
link:{url-download-keychecksum}netbeans-installers/{netbeans-version}/apache-netbeans_{netbeans-version}-1_all.deb.asc[PGP ASC])
* link:{url-download}netbeans-installers/{netbeans-version}/apache-netbeans-{netbeans-version}-0.noarch.rpm[apache-netbeans-{netbeans-version}-0.noarch.rpm] (link:{url-download-keychecksum}netbeans-installers/{netbeans-version}/apache-netbeans-{netbeans-version}-0.noarch.rpm.sha512[SHA-512],
link:{url-download-keychecksum}netbeans-installers/{netbeans-version}/apache-netbeans-{netbeans-version}-0.noarch.rpm.asc[PGP ASC])

- Source: link:{url-download}netbeans/{netbeans-version}/netbeans-{netbeans-version}-source.zip[netbeans-{netbeans-version}-source.zip] (link:{url-download-keychecksum}netbeans/{netbeans-version}/netbeans-{netbeans-version}-source.zip.sha512[SHA-512],
link:{url-download-keychecksum}netbeans/{netbeans-version}/netbeans-{netbeans-version}-source.zip.asc[PGP ASC])

////
NOTE: Using https below is highly recommended.
////
Officially, it is important that you link:https://www.apache.org/dyn/closer.cgi#verify[verify the integrity]
of the downloaded files using the PGP signatures (.asc file) or a hash (.sha512 files).
The PGP keys used to sign this release are available link:https://downloads.apache.org/netbeans/KEYS[here].

Apache NetBeans can also be installed as a self-contained link:https://snapcraft.io/netbeans[snap package] on Linux.

== Community Installers

IMPORTANT: Individual NetBeans committers may provide additional binary packages as a convenience.
While built using the Apache NetBeans release, they are not releases of the Apache Software
Foundation. They may include other contents (eg. JDK) under additional license terms.

- link:https://www.codelerity.com/netbeans/[Codelerity / Gj IT packages] - Windows, macOS and
Linux (.deb / .rpm / .AppImage) built with
link:https://github.com/apache/netbeans-nbpackage/[NBPackage]. Most
include a local JDK runtime for the IDE to run on, for a self-contained out-of-the-box
experience (other JDK's may be used for projects).

== Deployment Platforms

The Apache NetBeans {netbeans-version} binary releases require JDK 11+, and officially support running on JDK 11 and JDK 17.

TIP: Gradle projects in Apache NetBeans 16 are not supported when running the IDE on JDK 19.

== Building from Source

To build Apache NetBeans {netbeans-version} from source you need:

. A distribution of OpenJDK 11.
. Apache Ant 1.10 or greater (link:https://ant.apache.org[https://ant.apache.org]).

Once you have everything installed then:

1. Unzip link:{url-download}netbeans/{netbeans-version}/netbeans-{netbeans-version}-source.zip[netbeans-{netbeans-version}-source.zip]
in a directory of your liking.

[start=2]
. `cd` to that directory, and then run `ant` to build the Apache NetBeans IDE.
Once built you can run the IDE by typing `./nbbuild/netbeans/bin/netbeans`

== Community Approval

As in any other Apache Project, the Apache NetBeans Community approved this release
through the following voting processes in our xref:../../community/mailing-lists.adoc[mailing lists]:

- link:https://lists.apache.org/thread/xr1t60wpprlboco85s98n0nch8fgj87c[PMC vote]
- link:https://lists.apache.org/thread/oo6bmxtorb4rtn2v2dxqbq1hgp8tx4x6[PMC vote result]

== Earlier Releases

Please visit the xref:../index.adoc[Apache NetBeans Download page] for further details.

