////
     Licensed to the Apache Software Foundation (ASF) under one
     or more contributor license agreements.  See the NOTICE file
     distributed with this work for additional information
     regarding copyright ownership.  The ASF licenses this file
     to you under the Apache License, Version 2.0 (the
     "License"); you may not use this file except in compliance
     with the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing,
     software distributed under the License is distributed on an
     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
     KIND, either express or implied.  See the License for the
     specific language governing permissions and limitations
     under the License.
////
= Not found
:jbake-type: page
:jbake-tags: about
:jbake-status: published
:keywords: Apache NetBeans About
:description: About Apache NetBeans
:toc: left
:toc-title:
:icons: font

== Page not found

We regret having to say that the page you requested does not longer exist.

This may be a problem of ours, if so please feel free to link:https://netbeans.apache.org/participate/report-issue.html[report an issue].

== Main sections

This website is structured in these main sections:

=== Documentation

* The main link:https://netbeans.apache.org/help/index.html[documentation section].
** link:https://netbeans.apache.org/kb/docs/java/index.html[The Java SE Learning Trail].
** link:https://netbeans.apache.org/kb/docs/php/index.html[PHP and HTML5 Learning Trail].
** link:https://netbeans.apache.org/kb/docs/platform/index.html[The NetBeans Platform Learning Trail].

=== Other pages of interest:

* Our link:https://netbeans.apache.org/wiki/index.html[wiki is here].
* See how to link:https://netbeans.apache.org/community/index.html[participate in Apache NetBeans].
** Join our link:https://netbeans.apache.org/community/mailing-lists.html[mailing lists].
** See how you can link:https://netbeans.apache.org/participate/submit-pr.html[contribute code].
** See how you can link:https://netbeans.apache.org/kb/docs/contributing.html[contribute documentation].
** Contribute a link:https://plugins.netbeans.apache.org/[plugin] in our website.


