////
     Licensed to the Apache Software Foundation (ASF) under one
     or more contributor license agreements.  See the NOTICE file
     distributed with this work for additional information
     regarding copyright ownership.  The ASF licenses this file
     to you under the Apache License, Version 2.0 (the
     "License"); you may not use this file except in compliance
     with the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing,
     software distributed under the License is distributed on an
     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
     KIND, either express or implied.  See the License for the
     specific language governing permissions and limitations
     under the License.
////
= Welcome to Apache NetBeans
:jbake-type: page-noaside
:jbake-tags: main
:jbake-status: published
:keywords: My asciidoc keywords here!
:icons: font
:description: Apache NetBeans (incubating)
:note: The 'hero' tags below enable the 'hero' area in the page.gsp template
:hero.top: Version 9.0 Beta-rc3
:hero.title: Apache NetBeans
:hero.subtitle: Fits the Pieces Together

[.cards]
****

[.card]
.icon:users[] Community
Join the link:community/index.html[Apache NetBeans Community].

[.card]
.icon:wrench[] Participate
Find out the link:participate/index.html[many different ways you can participate] in the project.

[.card]
.icon:download[] Download
link:download/index.html[Download] the latest Apache NetBeans release.

****


