////
     Licensed to the Apache Software Foundation (ASF) under one
     or more contributor license agreements.  See the NOTICE file
     distributed with this work for additional information
     regarding copyright ownership.  The ASF licenses this file
     to you under the Apache License, Version 2.0 (the
     "License"); you may not use this file except in compliance
     with the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing,
     software distributed under the License is distributed on an
     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
     KIND, either express or implied.  See the License for the
     specific language governing permissions and limitations
     under the License.
////
= Events
:jbake-type: page
:jbake-tags: community
:jbake-status: published
:keywords: Apache NetBeans Events
:description: Apache NetBeans Events
:toc: left
:toc-title:

== Apache NetBeans Events

Users and developers either convoke or participate in different events and conferences. 

The Apache Software Foundation makes sure that all organizations are treated
fairly, making sure the project does not favor any commercial entities or
organizations over others.

In order to achieve those goals, the Apache NetBeans Project has to follow
link:https://cwiki.apache.org/confluence/display/NETBEANS/NetBeans+Events[some
guidelines] before announcing or promoting these events.

We are still working out those requirements, this page will then list
events of interest for the NetBeans Community.

=== Apache Software Foundation resources

The Apache Software Foundation provides different resources for events and conferences:

- link:https://www.apache.org/foundation/marks/events[Apache Event Branding Policy Overview].
- link:http://community.apache.org/speakers/slides.html[Apache related slides], see also more link:http://community.apache.org/speakers/index.html[Speaker Support Materials] 
and link:https://community.apache.org/speakers/[Speaker information], including an Apache press kit.
- The link:https://www.youtube.com/user/TheApacheFoundation/[ASF YouTube Channel] can be used to upload videos.
- You can list yourself as a link:http://community.apache.org/speakers/speakers.html[potential speaker].
- link:http://community.apache.org/calendars/conferences.html[Events calendar].
- link:https://www.apache.org/events/meetups.html[Upcoming Apache-Related meetups].

Be sure to also check the Apache Software Foundation link:http://community.apache.org/[Apache Community Development] page.




