////
     Licensed to the Apache Software Foundation (ASF) under one
     or more contributor license agreements.  See the NOTICE file
     distributed with this work for additional information
     regarding copyright ownership.  The ASF licenses this file
     to you under the Apache License, Version 2.0 (the
     "License"); you may not use this file except in compliance
     with the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing,
     software distributed under the License is distributed on an
     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
     KIND, either express or implied.  See the License for the
     specific language governing permissions and limitations
     under the License.
////
= Events
:jbake-type: page
:jbake-tags: community
:jbake-status: published
:keywords: Apache NetBeans Events Days
:description: Apache NetBeans Events
:toc: left
:toc-title:

== Apache NetBeans Events

Apache NetBeans Days are a class of events which happen regularly, with a clear definition of what makes an event be part of that class:

1. Have its opening keynote focus on the current state and roadmap of NetBeans. 
2. Have all demos done throughout the event in NetBeans.
3. Must be discussed/notified via the Apache NetBeans dev mailing list.

Note: From an Apache point of view what's important (besides trademarks being respected) is that all organizations are treated fairly and that it's clear that they cannot "own" the event or project. We need to make sure we don't favor commercial entities or organizations over others is a strong requirement of the ASF's 501c(3) status, so we're very picky about that. And besides this legal requirement, it's what makes the ASF a unique place where companies which might compete in the market can collaborate in a fair way, due to our very neutral status.

For publicizing NetBeans events, the Apache News posts at https://blogs.apache.org/foundation/ could mention those events, best is to contact press@apache.org for that. Apache has an Event Listing (https://events.apache.org/), that we'd also like to make use of.

=== Upcoming Apache NetBeans Days

Apache NetBeans Day UK 2018::
To be held at the University of Greenwich campus (London) on April the 27th, 2018. See the link:https://www.eventbrite.co.uk/e/apache-netbeans-day-uk-2018-tickets-43401128945[agenda and details] and the dedicated link:https://twitter.com/NetBeansDayUK[Twitter account].


=== Apache Software Foundation resources

The Apache Software Foundation provides different resources for events and conferences:

- link:https://www.apache.org/foundation/marks/events[Apache Event Branding Policy Overview].
- link:http://community.apache.org/speakers/slides.html[Apache related slides], see also more link:http://community.apache.org/speakers/index.html[Speaker Support Materials] 
and link:https://community.apache.org/speakers/[Speaker information], including an Apache press kit.
- The link:https://www.youtube.com/user/TheApacheFoundation/[ASF YouTube Channel] can be used to upload videos.
- You can list yourself as a link:http://community.apache.org/speakers/speakers.html[potential speaker].
- link:http://community.apache.org/calendars/conferences.html[Events calendar].
- link:https://www.apache.org/events/meetups.html[Upcoming Apache-Related meetups].

Be sure to also check the Apache Software Foundation link:http://community.apache.org/[Apache Community Development] page.




