////
     Licensed to the Apache Software Foundation (ASF) under one
     or more contributor license agreements.  See the NOTICE file
     distributed with this work for additional information
     regarding copyright ownership.  The ASF licenses this file
     to you under the Apache License, Version 2.0 (the
     "License"); you may not use this file except in compliance
     with the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing,
     software distributed under the License is distributed on an
     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
     KIND, either express or implied.  See the License for the
     specific language governing permissions and limitations
     under the License.
////
= Apache NetBeans Community
:jbake-type: page
:jbake-tags: community
:jbake-status: published
:keywords: Apache NetBeans Community
:description: Apache NetBeans Community
:toc: left
:toc-title:

== Stay Informed

The Apache NetBeans Community uses the link:mailing-lists.html[mailing lists] as the primary source of comunication. . See how to stay informed and in touch with other NetBeans users and developers.

== Participate
We welcome link:/participate/index.html[all kind of contributions]. And there are many ways to contribute: see how you can participate in Apache NetBeans.

== NetBeans Events
NetBeans users and developers participate in link:events.html[different events]. See how this works.

== Who We Are
The Apache NetBeans source code was donated by Oracle to the link:https://www.apache.org[Apache Software Foundation] in 2016.
Since then many contributors have joined the project. Find out link:who.html[who is who], and link:committer.html[how to become a committer].

== NekoBean
link:nekobean.html[NekoBean] is a mascot of Apache NetBeans Community.
