////
     Licensed to the Apache Software Foundation (ASF) under one
     or more contributor license agreements.  See the NOTICE file
     distributed with this work for additional information
     regarding copyright ownership.  The ASF licenses this file
     to you under the Apache License, Version 2.0 (the
     "License"); you may not use this file except in compliance
     with the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing,
     software distributed under the License is distributed on an
     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
     KIND, either express or implied.  See the License for the
     specific language governing permissions and limitations
     under the License.
////
= Apache NetBeans Community
:jbake-type: page
:jbake-tags: community
:jbake-status: published
:keywords: Apache NetBeans Community
:description: Apache NetBeans Community
:toc: left
:toc-title:

== Stay Informed

The Apache NetBeans Community uses the xref:mailing-lists.adoc[mailing lists] as the primary source of communication. See how to stay informed and in touch with other NetBeans users and developers.

== Participate
We welcome all kind of contributions. xref:../participate/index.adoc[See how you can participate in Apache NetBeans].

== NetBeans Events
NetBeans users and developers participate in different events. xref:events.adoc[See how this works].

== Who We Are
The Apache NetBeans source code was donated by Oracle to the link:https://www.apache.org[Apache Software Foundation] in 2016.
Since then many contributors have joined the project. Find out xref:who.adoc[who is who], and xref:committer.adoc[how to become a committer].

== NekoBean
xref:nekobean.adoc[NekoBean] is a mascot of Apache NetBeans Community.
