= bits.netbeans.org

bits.netbeans.org is a virtual host in the NetBeans VM.

== Infrastructure as code

The digital certificates and other virtual host settings are managed with
link:https://puppet.com/solutions/infrastructure-as-code[puppet], in a joint
effort between the NetBeans Team (for configuration) and the ASF-Infra Team
(for updates) through JIRA.

The NetBeans Team also maintains some convenience tools that generate Jenkins scripts
to ease JavaDoc generation. 

These infrastructure as code tools can be found here: https://github.com/apache/netbeans-tools/tree/master/buildscripts/conveniences

== The NetBeans APIs

Currently bits.netbeans.org hosts the APIs of NetBeans and different Maven stuff.

APIs are generated through different Jenkins jobs. Each hour a script in the
NetBeans VM checks if a download is required and downloads the API zip file.
Then, if required, the API zip file is extracted and served.

The Jenkins jobs responsible for generating the APIs are:

[options="header", cols="1,2,4"]
|===
| Release | Jenkins job | Generated API
| NetBeans Dev | link:https://builds.apache.org/job/netbeans-master-apidocmaven/[netbeans-master-apidocmaven] | https://bits.netbeans.org/dev/javadoc
| NetBeans 11.0 | link:https://builds.apache.org/job/netbeans-r110-apidocmaven/[netbeans-r110-apidocmaven] | https://bits.netbeans.org/11.0/javadoc/
| NetBeans 10.0 | link:https://builds.apache.org/job/netbeans-r100-apidocmaven/[netbeans-r100-apidocmaven] | https://bits.netbeans.org/10.0/javadoc/
| NetBeans 9.0 | link:https://builds.apache.org/job/netbeans-r90-apidocmaven/[netbeans-r90-apidocmaven] | https://bits.netbeans.org/9.0/javadoc/ 
| Maven Site | link:https://builds.apache.org/job/netbeans-mavenutils-website/[netbeans-mavenutils-website] | https://bits.netbeans.org/mavenutilities/nbm-shared/index.html

