// 
//     Licensed to the Apache Software Foundation (ASF) under one
//     or more contributor license agreements.  See the NOTICE file
//     distributed with this work for additional information
//     regarding copyright ownership.  The ASF licenses this file
//     to you under the Apache License, Version 2.0 (the
//     "License"); you may not use this file except in compliance
//     with the License.  You may obtain a copy of the License at
// 
//       http://www.apache.org/licenses/LICENSE-2.0
// 
//     Unless required by applicable law or agreed to in writing,
//     software distributed under the License is distributed on an
//     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
//     KIND, either express or implied.  See the License for the
//     specific language governing permissions and limitations
//     under the License.
//

= 1.5M Lines of NetBeans Code from Oracle to Apache
:author: Geertjan Wielenga
:revdate: 2018-06-21
:jbake-type: post
:jbake-tags: blogentry
:jbake-status: published
:keywords: Apache NetBeans blog index
:description: Apache NetBeans blog index
:toc: left
:toc-title:
:syntax: true

Great news: the process of completing the 2nd donation is now done and Oracle has made available a ZIP file constituting the 2nd donation. 
Oracle donated around 4,000,000 lines of code in the 1st donation last year and has now completed the 2nd 
donation constituting around 1,500,000 lines of code. This donation constitutes the modules of NetBeans dealing with 
enterprise Java, JavaScript, PHP, Groovy, as well as miscellaneous features applicable to Mobile and Web development.

We will continue to wrap up the final release of Apache NetBeans (incubating) 9.0, which will be focused on Java SE only. 
After that, or at least separate from that process, we will start relicensing the new code, i.e., from the 2nd donation, once it is in Apache NetBeans Git. 
Right now, it is a ZIP file, it needs to be moved to Apache NetBeans Git, and we need to do that in the right way, and figure out what the right way is.

This is a significant step forward in the transition of NetBeans from Oracle to Apache.