// 
//     Licensed to the Apache Software Foundation (ASF) under one
//     or more contributor license agreements.  See the NOTICE file
//     distributed with this work for additional information
//     regarding copyright ownership.  The ASF licenses this file
//     to you under the Apache License, Version 2.0 (the
//     "License"); you may not use this file except in compliance
//     with the License.  You may obtain a copy of the License at
// 
//       http://www.apache.org/licenses/LICENSE-2.0
// 
//     Unless required by applicable law or agreed to in writing,
//     software distributed under the License is distributed on an
//     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
//     KIND, either express or implied.  See the License for the
//     specific language governing permissions and limitations
//     under the License.
//

= [ANNOUNCE] Apache NetBeans 12.0 Released
:author: Geertjan Wielenga
:revdate: 2020-06-09
:jbake-type: post
:jbake-tags: blogentry
:jbake-status: published
:keywords: Apache NetBeans blog index
:description: Apache NetBeans blog index
:toc: left
:toc-title:
:syntax: true


Apache NetBeans 12.0 adds support for the latest Java language features, integrates new code donations from Oracle for Java Web development, 
enhances its best of breed Apache Maven tooling, brings multiple enhancements for users of Gradle, 
includes built-in features for Payara and WildFly for the first time, introduces new out of the box templates for JavaFX, 
upgrades and extends its PHP editor, provides new dark look and feel options, and includes a wide range of fixes.

All features provided by Apache NetBeans are supported out of the box, 
without additional plugins needing to be installed, and all for free. 
Apache NetBeans 12.0 is the first LTS release of NetBeans as a top level Apache project.

We would like to thank all contributors, the community, and the Apache Software Foundation for the great co-operation and enthusiasm 
enabling this complex and exciting project to continue to inspire and be of use to developers all over the world.


New & noteworthy features of the 12.0 release:

xref:../../download/nb120/index.adoc[Apache NetBeans 12.0 Features page]

Downloads:

xref:../../download/nb120/nb120.adoc[Apache NetBeans 12.0 Download page]

Feel free to share the good news!