// 
//     Licensed to the Apache Software Foundation (ASF) under one
//     or more contributor license agreements.  See the NOTICE file
//     distributed with this work for additional information
//     regarding copyright ownership.  The ASF licenses this file
//     to you under the Apache License, Version 2.0 (the
//     "License"); you may not use this file except in compliance
//     with the License.  You may obtain a copy of the License at
// 
//       http://www.apache.org/licenses/LICENSE-2.0
// 
//     Unless required by applicable law or agreed to in writing,
//     software distributed under the License is distributed on an
//     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
//     KIND, either express or implied.  See the License for the
//     specific language governing permissions and limitations
//     under the License.
//

= NetBeans at Oracle Code One 2019
:author: Geertjan Wielenga 
:revdate: 2019-09-11
:jbake-type: post
:jbake-tags: blogentry
:jbake-status: published
:keywords: NetBeans at Oracle Code One 2019
:description: NetBeans at Oracle Code One 2019
:toc: left
:toc-title:
:syntax: true

An Apache NetBeans schedule for those going to Oracle Code One 2019 next week!

*Saturday, September 14*

* 19:00 Hang out in the Thirsty Bear in Howard Street

*Monday, September 16*

* *Why You Should Be Coding with the NetBeans IDE* [BOF1321]
    Mark Stephens, Developer, IDRsolutions
    Ethan Price, Developer, IDRsolutions
    02:30 PM - 03:15 PM | Moscone South - Room 305

* *Java IDE Wars* [DEV1375]
    Ken Fogel, Teacher, Dawson College
    Scott Selikoff, Software Developer, Selikoff Solutions, LLC
    Jeanne Boyarsky, Developer, CodeRanch
    04:00 PM - 04:45 PM | Moscone South - Room 304

* *Hacking the NetBeans IDE* [BOF1338]
    Mark Stephens, IDR Solutions
    06:00 PM - 06:45 PM | Moscone South - Room 309

* *Hacking the NetBeans Profiler* [BOF4170]
    Ryan Cuprak, Formulation Applications R&D; Development Senior Manager, Dassault Systemes
    06:00 PM - 06:45 PM | Moscone South - Room 305

*Tuesday, September 17*

* *Getting Started with Deep Learning for Enterprise Java Developers* [DEV2126]
    Zoran Sevarac, Associate Professor, University of Belgrade, Faculty of Organisational Sciences
    Suyash Joshi, Developer Marketing Director, Oracle
    12:30 PM - 01:15 PM | Moscone South - Room 308

* *Testing on Oracle Autonomous Database with Homomorphic Encryption, Using NetBeans and Java - BYOL* [HOL3196]
    Simon Bain, Founder & CTO, ShieldIO
    12:30 PM - 02:30 PM | Moscone West - Room 3024C

*Wednesday, September 18*

* *Apache NetBeans: Its Status and Future* [DEV2506]
    Geertjan Wielenga, Product Manager, Oracle
    Mark Stephens, Developer, IDRsolutions
    Ethan Price, Developer, IDRsolutions
    06:00 PM - 06:45 PM | Moscone South - Room 206

*Thursday, September 19*

* *Testing on Oracle Autonomous Database with Homomorphic Encryption, Using NetBeans and Java - BYOL* [HOL3196]
    Simon Bain, Founder & CTO, ShieldIO
    09:00 AM - 11:00 AM | Moscone West - Room 3024C

* 19:00 Hang out in the Thirsty Bear in Howard Street