// 
//     Licensed to the Apache Software Foundation (ASF) under one
//     or more contributor license agreements.  See the NOTICE file
//     distributed with this work for additional information
//     regarding copyright ownership.  The ASF licenses this file
//     to you under the Apache License, Version 2.0 (the
//     "License"); you may not use this file except in compliance
//     with the License.  You may obtain a copy of the License at
// 
//       http://www.apache.org/licenses/LICENSE-2.0
// 
//     Unless required by applicable law or agreed to in writing,
//     software distributed under the License is distributed on an
//     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
//     KIND, either express or implied.  See the License for the
//     specific language governing permissions and limitations
//     under the License.
//

= Tentative Schedule for Apache NetBeans (incubating) 9.0 Release
:author: Geertjan Wielenga
:revdate: 2018-07-10
:jbake-type: post
:jbake-tags: blogentry
:jbake-status: published
:keywords: Apache NetBeans blog index
:description: Apache NetBeans blog index
:toc: left
:toc-title:
:syntax: true




We're currently running two processes, both of which it would be great if everyone would participate in -- and in fact it's really important that everyone does these two things:

. Vote in the PPMC thread:
+
link removed
+
Doing the above means more than putting a +1, it means downloading the sources, building them, looking at keys, etc, as described above.
. Fill out the Community Acceptance survey, which is focused on the functionality (versus the sources, which is what the PPMC thread is about), which takes about 5 minutes:
+
link removed
+
The Community Acceptance Survey runs until Sunday the 22nd of July. Issues found in the meantime will hopefully not be critical and not require a new voting candidate, but we'll need to see how things go and nothing can be guaranteed here of course -- i.e., someone could find a blocker of some kind during the community acceptance survey process.

Hopefully, nothing going wrong and everything going well, we'll then be at a point to start the IPMC vote thread on the 23rd and, if everything goes well, release Apache NetBeans (incubating) 9.0 at the beginning of August.

After that we'll work on the 2nd donation, relicensing it, moving it into master etc.
