// 
//     Licensed to the Apache Software Foundation (ASF) under one
//     or more contributor license agreements.  See the NOTICE file
//     distributed with this work for additional information
//     regarding copyright ownership.  The ASF licenses this file
//     to you under the Apache License, Version 2.0 (the
//     "License"); you may not use this file except in compliance
//     with the License.  You may obtain a copy of the License at
// 
//       http://www.apache.org/licenses/LICENSE-2.0
// 
//     Unless required by applicable law or agreed to in writing,
//     software distributed under the License is distributed on an
//     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
//     KIND, either express or implied.  See the License for the
//     specific language governing permissions and limitations
//     under the License.
//

= What's Happened to My Favorite NetBeans Plugins?
:author: Geertjan Wielenga
:revdate: 2018-07-20
:jbake-type: post
:jbake-tags: blogentry
:jbake-status: published
:keywords: Apache NetBeans blog index
:description: Apache NetBeans blog index
:toc: left
:toc-title:
:syntax: true




So, you start up xref:../../blogs/entry/tentative-schedule-for-apache-netbeans.adoc[Apache NetBeans (incubating) 9.0] and... you find that when you go to the New Project wizard, or when you try to open your projects, that there's no support for your JavaScript, PHP, Groovy, enterprise Java (i.e., Java EE or, as it is known now, Jakarta EE), and C/C++ projects.

What's the reason for that and what can be done?

Well, Apache NetBeans (incubating) 9.0 is specifically focused on Java SE only. Why? Because NetBeans is extremely large (it will be by far the largest project in Apache, once everything has been donated), which is because it has existed for over 20 years and provides support for a very wide range of technologies. Since so many files all needed to be audited before they could be donated to Apache, the decision was made to donate NetBeans in pieces, i.e., not everything at the same time because that would have taken much too long.

And since NetBeans is modular, doing an incremental donation was not difficult to architect. The first donation focused specifically on the underlying core, i.e., the NetBeans Platform (e.g., the module system, window system, menubar, etc etc) and, to enable the result of the first donation to be usable for general users and not just NetBeans Platform developers, the various Java SE features were included too, e.g., Java project templates, Java editor, and new Java features such as support for Jigsaw, JLink, and JShell.

The above is what Apache NetBeans (incubating) 9.0 consists of. In the meantime, the second donation has been completed, i.e., Oracle has audited and donated all the modules for features providing support for JavaScript, PHP, Groovy, and enterprise Java (i.e., Java EE or, as it is known now, Jakarta EE). These features are on a separate branch in the Apache NetBeans Git repo. They will be integrated, i.e., relicensed to Apache, after Apache NetBeans (incubating) 9.0 is released. After that, the next set of modules that is being audited prior to donation are related to C/C++.

So, does that mean that all the features that are not integrated into Apache NetBeans (incubating) 9.0 cannot be used? No, it does not. Go to Tools | Plugins in Apache NetBeans (incubating) 9.0 and, in the Settings tab, register the NetBeans IDE 8.2 update center:

\http://updates.netbeans.org/netbeans/updates/8.2/uc/final/distribution/catalog.xml.gz

Then go to the Available Plugins tab and you'll see all the plugins for NetBeans IDE 8.2., and search for the word "Kit", which will give you bundles of modules, for higher-level features such as C/C++, JavaScript, Groovy, PHP, and enterprise Java (i.e., Java EE or, as it is known now, Jakarta EE).

Though note that none of these features have been tested with Apache NetBeans (incubating) 9.0, 
they should work, in most cases. If not, don't panic. Just sign up to the Apache NetBeans mailing lists, 
as explained at xref:../index.adoc[netbeans.apache.org], and start a new thread where you'll highlight some problem you've encountered, 
after which someone will help you or you'll be advised to create a new issue in Apache NetBeans Issuezilla.

Where is all this documented, how can anyone know what will be donated in which order, etc? Easy, go here, to the end of this page:

link:https://cwiki.apache.org/confluence/display/NETBEANS/Apache+Transition[https://cwiki.apache.org/confluence/display/NETBEANS/Apache+Transition]
