// 
//     Licensed to the Apache Software Foundation (ASF) under one
//     or more contributor license agreements.  See the NOTICE file
//     distributed with this work for additional information
//     regarding copyright ownership.  The ASF licenses this file
//     to you under the Apache License, Version 2.0 (the
//     "License"); you may not use this file except in compliance
//     with the License.  You may obtain a copy of the License at
// 
//       http://www.apache.org/licenses/LICENSE-2.0
// 
//     Unless required by applicable law or agreed to in writing,
//     software distributed under the License is distributed on an
//     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
//     KIND, either express or implied.  See the License for the
//     specific language governing permissions and limitations
//     under the License.
//

= NetBeans Editor Component Palette Module Tutorial
:jbake-type: platform_tutorial
:jbake-tags: tutorials 
:jbake-status: published
:syntax: true
:source-highlighter: pygments
:toc: left
:toc-title:
:icons: font
:experimental:
:description: NetBeans Editor Component Palette Module Tutorial - Apache NetBeans
:keywords: Apache NetBeans Platform, Platform Tutorials, NetBeans Editor Component Palette Module Tutorial

This tutorial demonstrates how to create a component palette that provides drag-and-drop code snippets for a new file type. Code snippets serve to speed up coding. The IDE provides a component palette for JSP files, HTML files, and Form files. In this tutorial, you learn how to create a component palette for Java source files.

NOTE: This document uses NetBeans Platform 7.1 and NetBeans IDE 7.1. If you are using an earlier version, see  link:../70/nbm-palette-api2.html[the previous version of this document].








== Introduction to Component Palettes

In this tutorial, you implement several classes provided by the  link:http://bits.netbeans.org/dev/javadoc/org-netbeans-spi-palette/overview-summary.html[NetBeans Palette API]. Then you register the new component palette in the  ``layer.xml``  file, for the  ``text/x-java``  MIME type. The palette that you create in this way will only be visible if a Java source file is open.

If you do not want to create a new component palette, but only want to add a code snippet to an existing component palette, see the  link:nbm-palette-api1.html[NetBeans Code Snippet Module Tutorial].


== Setting up the Module Project

Before you start writing the module, you have to make sure you that your project is set up correctly. The IDE provides a wizard that sets up all the basic files needed for a module.


[start=1]
1. Choose File > New Project (Ctrl+Shift+N). Under Categories, select NetBeans Modules. Under Projects, select Module. Click Next.

[start=2]
1. In the Name and Location panel, type  ``JavaSourceFilePalette``  in the Project Name field. Change the Project Location to any directory on your computer. Click Next.

[start=3]
1. In the Basic Module Configuration panel, type  ``org.netbeans.modules.javasourcefilepalette``  in Code Name Base. Click Finish.

The IDE creates the  ``JavaSourceFilePalette``  project. The project contains all of your sources and project metadata, such as the project's Ant build script. The project opens in the IDE. You can view its logical structure in the Projects window (Ctrl-1) and its file structure in the Files window (Ctrl-2).


== Creating the Component Palette and Code Snippets


=== Specifying the Module's Dependencies

You will need to subclass several classes that belong to  link:http://bits.netbeans.org/dev/javadoc/index.html[NetBeans APIs]. Each has to be declared as a module dependency. Use the Project Properties dialog box for this purpose, as described below.


[start=1]
1. In the Projects window, right-click the  ``JavaSourceFilePalette``  project node and choose Properties. In the Project Properties dialog box, click Libraries.

[start=2]
1. 
For each of the following APIs, click "Add...", select the name from the Module list, and then click OK to confirm it:

* Common Palette
* Dialogs API
* Lookup API
* MIME Lookup API
* Nodes API
* Text API
* UI Utilities API
* Utilities API

[start=3]
1. Click OK to exit the Project Properties dialog box.

[start=4]
1. In the Projects window, expand the Important Files node, double-click the Project Metadata node, and note the long list of APIs that you selected have been declared as module dependencies.


=== Creating the Component Palette

Component Palettes are defined by the  link:http://bits.netbeans.org/dev/javadoc/org-netbeans-spi-palette/overview-summary.html[NetBeans Palette API]. Implementing the NetBeans Palette API for this tutorial means implementing the following NetBeans Palette API classes:

|===
|*File* |*Description* 

| `` link:http://bits.netbeans.org/dev/javadoc/org-netbeans-spi-palette/org/netbeans/spi/palette/PaletteFactory.html[PaletteFactory]``  |Creates a new instance of the Component Palette. To do so, it invokes the  ``createPalette``  method which creates a new palette from a specified folder registered in the  ``layer.xml`` . 

| `` link:http://bits.netbeans.org/dev/javadoc/org-netbeans-spi-palette/org/netbeans/spi/palette/PaletteController.html[PaletteController]``  |Provides access to data in the Component Palette. 

| `` link:http://bits.netbeans.org/dev/javadoc/org-netbeans-spi-palette/org/netbeans/spi/palette/PaletteActions.html[PaletteActions]``  |Provides the actions on the palette, categories, and items in the palette. 
|===

To use the Palette API to create the palette in this tutorial, take the following steps:


[start=1]
1. Right-click the  ``JavaSourceFilePalette``  project node and choose New > Java Class. Create a Java file called  ``JavaSourceFileLayerPaletteFactory`` .

[start=2]
1. Replace the default content of the  ``JavaSourceFileLayerPaletteFactory.java``  file with the following:

[source,java]
----

public class JavaSourceFileLayerPaletteFactory {
    
    //Name of the folder in the layer.xml file 
    //that is the root of the palette:
    public static final String JAVA_PALETTE_FOLDER = "JavaPalette";

    private static PaletteController palette = null;

    //Register the palette for the text/x-java MIME type:
    @MimeRegistration(mimeType = "text/x-java", service = PaletteController.class)
    public static PaletteController createPalette() {
        try {
            if (null == palette)
                palette = PaletteFactory.createPalette(
                        JAVA_PALETTE_FOLDER, 
                        new MyActions());
            return palette;
        } catch (IOException ex) {
            Exceptions.printStackTrace(ex);
        }
        return null;
    }

    private static class MyActions extends PaletteActions {

        //Add new buttons to the Palette Manager here:
        @Override
        public Action[] getImportActions() {
            return null;
        }

        //Add new contextual menu items to the palette here:
        @Override
        public Action[] getCustomPaletteActions() {
            return null;
        }

        //Add new contextual menu items for palette categories here:
        @Override
        public Action[] getCustomCategoryActions(Lookup arg0) {
            return null;
        }

        //Add new contextual menu items for palette items here:
        @Override
        public Action[] getCustomItemActions(Lookup arg0) {
            return null;
        }

        //Define the double-click action here:
        @Override
        public Action getPreferredAction(Lookup arg0) {
            return null;
        }

    }
    
}
----


=== Adding a DragAndDropHandler

In this section, we change the  ``PaletteController`` , in the code above, and add a  ``DragAndDropHandler`` . In doing so, we will let the user drag code snippets FROM the editor INTO the palette:


[source,java]
----

@MimeRegistration(mimeType = "text/x-java", service = PaletteController.class)
public static PaletteController createPalette() {
    try {
        if (null == palette) {
            *//Add null for the PaletteFilter, which we are not using here,
            //and then instantiate your implementation of the DragAndDropHandler*:
            palette = PaletteFactory.createPalette(
                        JAVA_PALETTE_FOLDER,
                        new MyActions(),
                        *null,
                        new MyDragAndDropHandler()*); 
        }
        return palette;
    } catch (IOException ex) {
        Exceptions.printStackTrace(ex);
    }
    return null;
}

*//Definition of the DragAndDropHandler:
private static class MyDragAndDropHandler extends DragAndDropHandler {

    MyDragAndDropHandler() {
        super(true);
    }

    //Maybe you don't like the default 'add to palette' implementation,
    //so you could create your own here:
    @Override
    public void customize(ExTransferable t, Lookup item) {
    }

}*
----

The above default implementation is all you need. Now the user will be able to drag from the editor into the palette.


=== Creating the Code Snippets

Each code snippet requires the following files:

* A Java class that defines the piece of code to be dragged into the Source Editor. This Java class must refer to  ``JavaSourceFilePaletteUtilities.java`` , which defines how the piece of code should be inserted. For example, indentation and formatting are defined here.
* Optionally, a customizer where the user can type something that will be added to the snippet, such as comments.
* A properties file that defines the labels and tooltips.
* A 16x16 pixel image for the 'Small Icon' display.
* A 32x32 pixel image for the 'Big Icon' display.

After you have created or added the above files to the NetBeans module, you declare them in a resource declaration XML file, which you register in the NetBeans System Filesystem by using the  ``layer.xml``  file, as follows:


[source,xml]
----

<folder name="JavaPalette">
    <folder name="Items">
        <attr name="SystemFileSystem.localizingBundle" stringvalue="org.netbeans.modules.javasourcefilepalette.Bundle"/>
        <file name="Item.xml" url="resources/Item.xml">
            <attr name="SystemFileSystem.localizingBundle" stringvalue="org.netbeans.modules.javasourcefilepalette.Bundle"/>
        </file>
    </folder>
</folder>
----

For all the details on the items above, work through the  link:nbm-palette-api1.html[NetBeans Code Snippet Module Tutorial].


== Building and Installing the Module

The IDE uses an Ant build script to build and install your module. The build script is created for you when you create the module project.


[start=1]
1. In the Projects window, right-click the  ``JavaSourceFilePalette``  project and choose Run. The module is built and installed in the target platform. The target platform opens so that you can try out your new module. The default target platform is the installation used by the current instance of the development IDE.


[start=2]
1. Verify that the module is correctly installed by using it.
link:http://netbeans.apache.org/community/mailing-lists.html[Send Us Your Feedback]


== Next Steps

For more information about creating and developing NetBeans modules, see the following resources:

*  link:https://netbeans.apache.org/kb/docs/platform.html[Other Related Tutorials]
*  link:http://bits.netbeans.org/dev/javadoc/index.html[NetBeans API Javadoc]
