////
     Licensed to the Apache Software Foundation (ASF) under one
     or more contributor license agreements.  See the NOTICE file
     distributed with this work for additional information
     regarding copyright ownership.  The ASF licenses this file
     to you under the Apache License, Version 2.0 (the
     "License"); you may not use this file except in compliance
     with the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing,
     software distributed under the License is distributed on an
     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
     KIND, either express or implied.  See the License for the
     specific language governing permissions and limitations
     under the License.
////
////

NOTE: 
See https://www.apache.org/dev/release-download-pages.html 
for important requirements for download pages for Apache projects.

////
= Downloading Apache NetBeans 12.0 
:jbake-type: page_noaside
:jbake-tags: download
:jbake-status: published
:keywords: Apache NetBeans 12.0 Download
:description: Apache NetBeans 12.0 Download
:toc: left
:toc-title:
:icons: font
:syntax: true
:source-highlighter: pygments

Apache NetBeans 12.0 was released on June 4, 2020.
See xref:index.adoc[Apache NetBeans 12.0 Features] for a full list of features.

////
NOTE: It's mandatory to link to the source. It's optional to link to the binaries.
NOTE: It's mandatory to link against https://www.apache.org for the sums & keys. https is recommended.
NOTE: It's NOT recommended to link to github.
////
Apache NetBeans 12.0 is available for download from your closest Apache mirror.

- Binaries: 
link:https://archive.apache.org/dist/netbeans/netbeans/12.0/netbeans-12.0-bin.zip[netbeans-12.0-bin.zip] (link:https://archive.apache.org/dist/netbeans/netbeans/12.0/netbeans-12.0-bin.zip.sha512[SHA-512],
link:https://archive.apache.org/dist/netbeans/netbeans/12.0/netbeans-12.0-bin.zip.asc[PGP ASC])

- Source: link:https://archive.apache.org/dist/netbeans/netbeans/12.0/netbeans-12.0-source.zip[netbeans-12.0-source.zip] 
(link:https://archive.apache.org/dist/netbeans/netbeans/12.0/netbeans-12.0-source.zip.sha512[SHA-512],
link:https://archive.apache.org/dist/netbeans/netbeans/12.0/netbeans-12.0-source.zip.asc[PGP ASC])

- Installers: 

* link:https://archive.apache.org/dist/netbeans/netbeans/12.0/Apache-NetBeans-12.0-bin-windows-x64.exe[Apache-NetBeans-12.0-bin-windows-x64.exe] (link:https://archive.apache.org/dist/netbeans/netbeans/12.0/Apache-NetBeans-12.0-bin-windows-x64.exe.sha512[SHA-512],
link:https://archive.apache.org/dist/netbeans/netbeans/12.0/Apache-NetBeans-12.0-bin-windows-x64.exe.asc[PGP ASC])
* link:https://archive.apache.org/dist/netbeans/netbeans/12.0/Apache-NetBeans-12.0-bin-linux-x64.sh[Apache-NetBeans-12.0-bin-linux-x64.sh] (link:https://archive.apache.org/dist/netbeans/netbeans/12.0/Apache-NetBeans-12.0-bin-linux-x64.sh.sha512[SHA-512],
link:https://archive.apache.org/dist/netbeans/netbeans/12.0/Apache-NetBeans-12.0-bin-linux-x64.sh.asc[PGP ASC])
* link:https://archive.apache.org/dist/netbeans/netbeans/12.0/Apache-NetBeans-12.0-bin-macosx.dmg[Apache-NetBeans-12.0-bin-macosx.dmg] (link:https://archive.apache.org/dist/netbeans/netbeans/12.0/Apache-NetBeans-12.0-bin-macosx.dmg.sha512[SHA-512],
link:https://archive.apache.org/dist/netbeans/netbeans/12.0/Apache-NetBeans-12.0-bin-macosx.dmg.asc[PGP ASC])

- Javadoc for this release is available at https://bits.netbeans.org/12.0/javadoc

////
NOTE: Using https below is highly recommended.
////
Officially, it is important that you link:https://www.apache.org/dyn/closer.cgi#verify[verify the integrity]
of the downloaded files using the PGP signatures (.asc file) or a hash (.sha512 files).
The PGP signatures should be matched against the link:https://downloads.apache.org/netbeans/KEYS[KEYS] file which contains the PGP keys used to sign this release.

Apache NetBeans can also be installed as a self-contained link:https://snapcraft.io/netbeans[snap package] on Linux.

== Deployment platforms

Apache NetBeans 12.0 runs on the JDK LTS releases 8 and 11, as well as on JDK 14, i.e., the current JDK release at the time of this NetBeans release.

== Community approval

As in any other Apache Project, the Apache NetBeans Community approved this release
through the following voting processes in our xref:../../community/mailing-lists.adoc[mailing lists]:

- link:https://lists.apache.org/thread.html/r0dd18c0214939423e84c429d492b38d938acc3063dfd39252a8a03ed%40%3Cdev.netbeans.apache.org%3E[PMC vote]
- link:https://lists.apache.org/thread.html/r963280a9406f4310cc8798d63f901674656794f497e04559cc32f53b%40%3Cdev.netbeans.apache.org%3E[PMC vote result]

Because 12.0 is an LTS release, the link:https://cwiki.apache.org/confluence/display/NETBEANS/NetCAT+FAQ[NetCAT community acceptance process] is applicable, with the results of NetCAT 12.0 available here:

- link:https://cwiki.apache.org/confluence/display/NETBEANS/Results+from+Apache+NetBeans+IDE+12.0+Community+Acceptance+survey[Results from Apache NetBeans IDE 12.0 Community Acceptance survey]

== Known problems

- Maven project may fail to be updated when the pom.xml is changed or dependencies
  are updated. As a workaround add the commandline option
  `-J-Dmaven.defaultProjectBuilder.disableGlobalModelCache=true`  to the
  `netbeans_default_options` in the `etc/netbeans.conf` configuration file:
+
[source,bash]
----

netbeans_default_options="-J-Dmaven.defaultProjectBuilder.disableGlobalModelCache=true -J-XX:+UseStringDeduplication -J-Xss2m  -J-Djdk.gtk.version=2.2 -J-Dapple.laf.useScreenMenuBar=true -J-Dapple.awt.graphics.UseQuartz=true -J-Dsun.java2d.noddraw=true -J-Dsun.java2d.dpiaware=true -J-Dsun.zip.disableMemoryMapping=true -J-Dplugin.manager.check.updates=false -J-Dnetbeans.extbrowser.manual_chrome_plugin_install=yes -J--add-opens=java.base/java.net=ALL-UNNAMED -J--add-opens=java.base/java.lang.ref=ALL-UNNAMED -J--add-opens=java.base/java.lang=ALL-UNNAMED -J--add-opens=java.base/java.security=ALL-UNNAMED -J--add-opens=java.base/java.util=ALL-UNNAMED -J--add-opens=java.desktop/javax.swing.plaf.basic=ALL-UNNAMED -J--add-opens=java.desktop/javax.swing.text=ALL-UNNAMED -J--add-opens=java.desktop/javax.swing=ALL-UNNAMED -J--add-opens=java.desktop/java.awt=ALL-UNNAMED -J--add-opens=java.desktop/java.awt.event=ALL-UNNAMED -J--add-opens=java.prefs/java.util.prefs=ALL-UNNAMED -J--add-opens=jdk.jshell/jdk.jshell=ALL-UNNAMED -J--add-modules=jdk.jshell -J--add-exports=java.desktop/sun.awt=ALL-UNNAMED -J--add-exports=java.desktop/java.awt.peer=ALL-UNNAMED -J--add-exports=java.desktop/com.sun.beans.editors=ALL-UNNAMED -J--add-exports=java.desktop/sun.swing=ALL-UNNAMED -J--add-exports=java.desktop/sun.awt.im=ALL-UNNAMED -J--add-exports=jdk.internal.jvmstat/sun.jvmstat.monitor=ALL-UNNAMED -J--add-exports=java.management/sun.management=ALL-UNNAMED -J--add-exports=java.base/sun.reflect.annotation=ALL-UNNAMED -J-XX:+IgnoreUnrecognizedVMOptions"

----

== Earlier releases

Please visit the xref:../index.adoc[Apache NetBeans Download page] for further details.
