////
     Licensed to the Apache Software Foundation (ASF) under one
     or more contributor license agreements.  See the NOTICE file
     distributed with this work for additional information
     regarding copyright ownership.  The ASF licenses this file
     to you under the Apache License, Version 2.0 (the
     "License"); you may not use this file except in compliance
     with the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing,
     software distributed under the License is distributed on an
     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
     KIND, either express or implied.  See the License for the
     specific language governing permissions and limitations
     under the License.
////
////

NOTE: 
See https://www.apache.org/dev/release-download-pages.html 
for important requirements for download pages for Apache projects.

////
= Downloading Apache NetBeans 12.4 
:jbake-type: page_noaside
:jbake-tags: download
:jbake-status: published
:keywords: Apache NetBeans 12.4 Download
:description: Apache NetBeans 12.4 Download
:toc: left
:toc-title:
:icons: font

Apache NetBeans 12.4 was released May 19, 2021. See link:/download/nb124/index.html[Apache NetBeans 12.4 Features] for a full list of features.
